#!/usr/bin/env python3
"""Generate every Subway Seat port into dist/, plus the website's tokens.

    ./build.py                 # everything
    ./build.py --only vscode   # one or more ports (comma-separated)
    ./build.py --list          # show discovered ports

Each module in ports/ (see ports/_lib.py for the contract) returns its files for
all flavors; this script writes them to dist/<port-id>/, checks that structured
files parse, and records everything in dist/manifest.json for the site and docs.
"""

import argparse
import importlib
import json
import pkgutil
import plistlib
import shutil
import sys
import tomllib
import xml.etree.ElementTree as ET
from pathlib import Path

try:  # optional: `uv run --with pyyaml ./build.py` also validates YAML
    import yaml
except ImportError:
    yaml = None

import palette as p
import ports
from ports._lib import CATEGORIES, Out

ROOT = Path(__file__).parent
DIST = ROOT / "dist"
SITE_THEME = ROOT / "site" / "src" / "theme"


def discover():
    mods = {}
    for info in pkgutil.iter_modules(ports.__path__):
        if info.name.startswith("_"):
            continue
        mod = importlib.import_module(f"ports.{info.name}")
        mods[mod.META["id"]] = mod
    return dict(
        sorted(mods.items(), key=lambda kv: (CATEGORIES.index(kv[1].META["category"]), kv[1].META["name"].lower()))
    )


def check(path: Path, content):
    """Parse structured files so a broken template fails the build."""
    if isinstance(content, bytes):
        return
    suffix = path.suffix.lower()
    try:
        if suffix == ".json":
            json.loads(content)
        elif suffix == ".toml":
            tomllib.loads(content)
        elif suffix in {".plist", ".tmtheme", ".itermcolors", ".xccolortheme"}:
            plistlib.loads(content.encode())
        elif suffix in {".xml", ".icls", ".svg"}:
            ET.fromstring(content)
        elif suffix in {".yml", ".yaml"} and yaml is not None:
            yaml.safe_load(content)
    except Exception as e:  # noqa: BLE001 — report any parser's error the same way
        raise SystemExit(f"✗ {path.relative_to(ROOT)} does not parse: {e}") from e


def vars_for(f):
    return {"name": f.name, "slug": f.slug, "snake": f.snake, "id": f.id}


def run_port(mod):
    meta = mod.META
    outs: list[Out] = mod.build(p.FLAVORS)
    shutil.rmtree(DIST / meta["id"], ignore_errors=True)  # no stale files from renamed outputs
    files = []
    for out in outs:
        path = DIST / meta["id"] / out.path
        path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(out.content, bytes):
            path.write_bytes(out.content)
        else:
            path.write_text(out.content)
        if path.suffix in {".sh", ".fish"} or path.parent.name == "bin":
            path.chmod(0o755)
        check(path, out.content)
        files.append({
            "path": f"{meta['id']}/{out.path}",
            "flavor": out.flavor,
            "dest": out.dest,
            "lang": out.lang,
            "append": out.append,
            "binary": isinstance(out.content, bytes),
        })
    enable = meta.get("enable")
    return {
        **{k: v for k, v in meta.items() if k != "enable"},
        "enable": {f.id: {**enable, "code": enable["code"].format(**vars_for(f))} for f in p.FLAVORS}
        if enable
        else None,
        "files": files,
    }


# ── Website tokens (site/src/theme) ────────────────────────────────────────
def camel(key):
    head, *rest = key.split("_")
    return head + "".join(w.title() for w in rest)


def write_site_tokens():
    SITE_THEME.mkdir(parents=True, exist_ok=True)
    header = "// Generated by build.py from palette.py — edit the palette, not this file."
    walnut = "\n".join(f'  {camel(r)}: "{p.DEFAULT.colors[r]}",' for r in p.ROLES)
    (SITE_THEME / "tokens.stylex.ts").write_text(
        f'{header}\nimport * as stylex from "@stylexjs/stylex";\n\n'
        f"export const color = stylex.defineVars({{\n{walnut}\n}});\n"
    )
    themes = "\n\n".join(
        f"export const {f.id} = stylex.createTheme(color, {{\n"
        + "\n".join(f'  {camel(r)}: "{f.colors[r]}",' for r in p.ROLES)
        + "\n});"
        for f in p.FLAVORS
    )
    (SITE_THEME / "flavors.ts").write_text(
        f'{header}\nimport * as stylex from "@stylexjs/stylex";\nimport {{ color }} from "./tokens.stylex";\n\n{themes}\n'
    )
    data = {
        "roles": [camel(r) for r in p.ROLES],
        "ground": [camel(r) for r in p.GROUND],
        "text": [camel(r) for r in p.TEXT],
        "accents": [camel(r) for r in p.ACCENTS],
        "roleNames": {camel(k): v for k, v in p.ROLE_NAMES.items()},
        "accentRoles": {camel(k): v for k, v in p.ACCENT_ROLES.items()},
        "flavors": [
            {
                "id": f.id,
                "name": f.name,
                "slug": f.slug,
                "dark": f.dark,
                "blurb": f.blurb,
                "colors": {camel(r): f.colors[r] for r in p.ROLES},
                "ansi": [camel(r) for r in f.ansi_roles],
            }
            for f in p.FLAVORS
        ],
    }
    (SITE_THEME / "palette.json").write_text(json.dumps(data, indent=2) + "\n")
    print("  site/src/theme/{tokens.stylex.ts, flavors.ts, palette.json}")


# ── README port table (between the markers) ───────────────────────────────
README = ROOT / "README.md"
START, END = "<!-- ports:start -->", "<!-- ports:end -->"


def write_readme_ports(entries):
    if not README.exists() or START not in README.read_text():
        return
    rows = []
    for category in CATEGORIES:
        ports_in = [e for e in entries.values() if e["category"] == category]
        if not ports_in:
            continue
        links = ", ".join(f"[{e['name']}](dist/{e['id']})" for e in sorted(ports_in, key=lambda e: e["name"].lower()))
        rows.append(f"| **{category}** ({len(ports_in)}) | {links} |")
    table = "| | |\n|---|---|\n" + "\n".join(rows)
    text = README.read_text()
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    README.write_text(f"{head}{START}\n{table}\n{END}{tail}")
    print(f"  README.md ports table ({len(entries)} ports)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma-separated port ids")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--no-manifest", action="store_true", help="write files only (safe for parallel runs)")
    args = ap.parse_args()

    if args.only and not args.list:
        # Import only what was asked for, so a half-written port elsewhere can't break this run.
        mods = {}
        for pid in args.only.split(","):
            try:
                mods[pid] = importlib.import_module(f"ports.{pid.replace('-', '_')}")
            except ModuleNotFoundError:
                sys.exit(f"unknown port: {pid} (expected ports/{pid.replace('-', '_')}.py)")
    else:
        mods = discover()
    if args.list:
        for pid, mod in mods.items():
            print(f"{mod.META['category']:<15} {pid:<20} {mod.META['name']}")
        print(f"{len(mods)} ports")
        return

    wanted = set(args.only.split(",")) if args.only else set(mods)
    if unknown := wanted - set(mods):
        sys.exit(f"unknown port(s): {', '.join(sorted(unknown))}")

    manifest_path = DIST / "manifest.json"
    previous = {}
    if args.only and manifest_path.exists():
        previous = {e["id"]: e for e in json.loads(manifest_path.read_text())["ports"]}

    entries = {}
    for pid, mod in mods.items():
        if pid in wanted:
            entries[pid] = run_port(mod)
            print(f"  ✓ {pid:<20} {len(entries[pid]['files'])} files")
        elif pid in previous:
            entries[pid] = previous[pid]

    if args.no_manifest:
        print(f"{len(wanted)} ports written (manifest untouched)")
        return

    manifest = {
        "flavors": [{"id": f.id, "name": f.name, "slug": f.slug, "dark": f.dark} for f in p.FLAVORS],
        "categories": CATEGORIES,
        "ports": list(entries.values()),
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    if not args.only:
        write_site_tokens()
        write_readme_ports(entries)
        # Anything in dist/ that no port owns is left over from an old layout.
        for stale in sorted(set(x.name for x in DIST.iterdir()) - set(entries) - {"manifest.json"}):
            print(f"  removed stale dist/{stale}")
            target = DIST / stale
            shutil.rmtree(target) if target.is_dir() else target.unlink()
    print(f"{len(entries)} ports in dist/")


if __name__ == "__main__":
    main()
