"""Notepad++: an XML theme per flavor, covering every lexer in Notepad++'s stylers.model.xml."""

import re
from xml.sax.saxutils import quoteattr

from ports._editors import ui
from ports._lib import HEADER, Out, h

META = {
    "id": "notepad-plus-plus",
    "name": "Notepad++",
    "category": "Editors",
    "homepage": "https://notepad-plus-plus.org",
    "enable": {
        "where": "Settings › Style Configurator, after copying the file to %AppData%\\Notepad++\\themes "
        "(a portable install uses the themes folder next to notepad++.exe) and restarting Notepad++",
        "code": "Select theme: {name}",
        "lang": "text",
    },
    "notes": "",  # set below, once the lexers are counted
}

# Lexer name|description, then "styleID NAME[=keywordClass]" entries (from Notepad++'s stylers.model.xml).
# "*user" stands for the eight USER KEYWORDS substyles (128–135).
LEXERS = """
java|Java
    11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING; 7 CHARACTER; 10
    OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15 COMMENT LINE DOC;
    17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; *user
cmake|CMake
    0 DEFAULT; 1 COMMENT; 2 STRING D; 3 STRING L; 4 STRING R; 5 COMMAND=instre1; 6 PARAMETER; 7
    VARIABLE; 8 USER DEFINED=type1; 9 WHILEDEF; 10 FOREACHDEF; 11 IFDEF; 12 MACRODEF; 13 STRING
    VARIABLE; 14 NUMBER
c|C
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING;
    7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15
    COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23 PREPROCESSOR COMMENT;
    24 PREPROCESSOR COMMENT DOC; *user
cpp|C++
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING;
    20 STRINGRAW; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3
    COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23
    PREPROCESSOR COMMENT; 24 PREPROCESSOR COMMENT DOC; *user
diff|diff file
    0 DEFAULT; 1 COMMENT; 2 COMMAND; 3 HEADER; 4 POSITION; 5 DELETED; 6 ADDED
rust|Rust
    32 DEFAULT; 0 WHITESPACE; 1 BLOCK COMMENT; 2 LINE COMMENT; 3 BLOCK DOC COMMENT; 4 LINE DOC
    COMMENT; 5 NUMBER; 6 KEYWORDS 1=instre1; 7 KEYWORDS 2=instre2; 8 KEYWORDS 3=type1; 9 KEYWORDS
    4=type2; 10 KEYWORDS 5=type3; 11 KEYWORDS 6=type4; 12 KEYWORDS 7=type5; 13 REGULAR STRING; 14
    RAW STRING; 15 CHARACTER; 16 OPERATOR; 17 IDENTIFIER; 18 LIFETIME; 19 MACRO; 20 LEXICAL ERROR;
    21 BYTE STRING; 22 RAW BYTE STRING; 23 BYTE CHARACTER; 24 C STRING; 25 RAW C STRING
xml|XML
    12 XML START; 13 XML END; 0 DEFAULT; 9 COMMENT; 5 NUMBER; 6 DOUBLE STRING; 7 SINGLE STRING; 1
    TAG; 11 TAG END; 2 TAG UNKNOWN; 3 ATTRIBUTE; 4 ATTRIBUTE UNKNOWN; 21 SGML DEFAULT; 22 SGML
    COMMAND=instre1; 23 SGML 1ST PARAM; 24 SGML DOUBLESTRING; 25 SGML SIMPLESTRING; 31 SGML BLOCK
    DEFAULT; 17 CDATA; 10 ENTITY; 192 USER ATTRIBUTES 1=substyle1; 193 USER ATTRIBUTES 2=substyle2;
    194 USER ATTRIBUTES 3=substyle3; 195 USER ATTRIBUTES 4=substyle4; 196 USER ATTRIBUTES
    5=substyle5; 197 USER ATTRIBUTES 6=substyle6; 198 USER ATTRIBUTES 7=substyle7; 199 USER
    ATTRIBUTES 8=substyle8
html|HTML
    0 DEFAULT; 9 COMMENT; 5 NUMBER; 6 DOUBLE STRING; 7 SINGLE STRING; 1 TAG=instre1; 11 TAG END; 2
    TAG UNKNOWN; 3 ATTRIBUTE; 4 ATTRIBUTE UNKNOWN; 21 SGML DEFAULT; 22 SGML COMMAND=instre2; 23 SGML
    1ST PARAM; 24 SGML DOUBLESTRING; 25 SGML SIMPLESTRING; 31 SGML BLOCK DEFAULT; 17 CDATA; 19
    VALUE; 10 ENTITY; 192 USER TAGS1=substyle1; 193 USER TAGS2=substyle2; 194 USER TAGS3=substyle3;
    195 USER TAGS4=substyle4; 196 USER ATTRIBUTES1=substyle5; 197 USER ATTRIBUTES2=substyle6; 198
    USER ATTRIBUTES3=substyle7; 199 USER ATTRIBUTES4=substyle8
css|CSS
    0 DEFAULT; 1 TAG; 2 CLASS; 3 PSEUDOCLASS=instre2; 4 UNKNOWN PSEUDOCLASS; 5 OPERATOR; 6
    IDENTIFIER=instre1; 7 UNKNOWN IDENTIFIER; 8 VALUE; 9 COMMENT; 10 ID; 11 IMPORTANT; 12 DIRECTIVE;
    13 DOUBLE STRING; 14 SINGLE STRING; 16 ATTRIBUTE; 18 PSEUDOELEMENT=type3; 20 LEGACY
    PSEUDOELEMENT=type5; 22 MEDIA; 23 VARIABLE
cs|C#
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING;
    7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15
    COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23 PREPROCESSOR COMMENT;
    24 PREPROCESSOR COMMENT DOC; *user
sql|SQL
    5 KEYWORD=instre1; 16 USER1=instre2; 19 KEYWORD2=type3; 4 NUMBER; 6 STRING; 7 STRING2; 10
    OPERATOR; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 24 Q OPERATOR
json|JSON
    0 DEFAULT; 1 NUMBER; 2 STRING; 3 STRING EOL; 4 PROPERTY NAME; 5 ESCAPE SEQUENCE; 6 LINE COMMENT;
    7 BLOCK COMMENT; 8 OPERATOR; 9 URI; 10 COMPACT IRI; 11 KEYWORD=instre1; 12 LD KEYWORD=instre2;
    13 ERROR
javascript|JavaScript (embedded)
    41 DEFAULT; 45 NUMBER; 46 WORD; 47 KEYWORD=instre1; 48 DOUBLE STRING; 49 SINGLE STRING; 53
    TEMPLATE LIT. (CLIENT); 68 TEMPLATE LIT. (SERVER); 50 SYMBOLS; 52 REGEX; 42 COMMENT; 43 COMMENT
    LINE; 44 COMMENT DOC; 200 USER KEYWORDS 1=substyle1; 201 USER KEYWORDS 2=substyle2; 202 USER
    KEYWORDS 3=substyle3; 203 USER KEYWORDS 4=substyle4; 204 USER KEYWORDS 5=substyle5; 205 USER
    KEYWORDS 6=substyle6; 206 USER KEYWORDS 7=substyle7; 207 USER KEYWORDS 8=substyle8
javascript.js|JavaScript
    11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 19 WINDOW INSTRUCTION=instre2; 4
    NUMBER; 6 STRING; 20 STRING RAW; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2
    COMMENT LINE; 3 COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD
    ERROR; *user
tcl|TCL
    0 DEFAULT; 10 MODIFIER; 11 EXPAND=type3; 12 TCL KEYWORD=instre1; 13 iTCL KEYWORD=type1; 14 TK
    KEYWORD=instre2; 15 TK COMMAND=type2; 3 NUMBER; 9 SUB BRACE; 8 SUBSTITUTION; 6 OPERATOR; 7
    IDENTIFIER; 4 WORD IN QUOTE; 5 IN QUOTE; 1 COMMENT; 2 COMMENT LINE; 20 COMMENT BOX; 21 BLOCK
    COMMENT; 16 USER1=type4; 17 USER2=type5; 18 USER3=type6; 19 USER4=type7
toml|TOML
    0 DEFAULT; 1 COMMENT; 2 IDENTIFIER; 3 KEYWORD=instre1; 4 NUMBER; 5 TABLE; 6 KEY; 7 ERROR; 8
    OPERATOR; 9 STRING SQ; 10 STRING DQ; 11 TRIPLE STRING SQ; 12 TRIPLE STRING DQ; 13 ESCAPE CHAR;
    14 DATETIME
typescript|TypeScript
    11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 19 WINDOW INSTRUCTION; 4 NUMBER; 6
    STRING; 20 STRING RAW; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT
    LINE; 3 COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR;
    *user
python|Python
    0 DEFAULT; 1 COMMENT LINE; 2 NUMBER; 3 STRING; 4 CHARACTER; 5 KEYWORDS=instre1; 6 TRIPLE; 7
    TRIPLE DOUBLE; 8 CLASS NAME; 9 DEF NAME; 10 OPERATOR; 11 IDENTIFIER; 12 COMMENT BLOCK; 14
    BUILTINS=instre2; 15 DECORATOR; 20 ATTRIBUTE; 16 F STRING; 17 F CHARACTER; 18 F TRIPLE; 19 F
    TRIPLEDOUBLE; *user
batch|Batch
    0 DEFAULT; 1 COMMENT; 2 KEYWORDS=instre1; 3 LABEL; 4 HIDE SYMBOL; 5 COMMAND; 6 VARIABLE; 7
    OPERATOR; 8 AFTER LABEL
ini|INI file
    0 DEFAULT; 1 COMMENT; 2 SECTION; 3 ASSIGNMENT; 4 DEFVAL; 5 KEY
inno|InnoSetup
    0 DEFAULT; 1 COMMENT; 2 KEYWORD=instre2; 3 PARAMETER=type1; 4 SECTION=instre1; 5
    PREPROCESSOR=type2; 6 PREPROCESSOR INLINE; 7 COMMENT PASCAL; 8 KEYWORD PASCAL=type3; 9 KEYWORD
    USER=type4; 10 STRING DOUBLE; 11 STRING SINGLE; 12 IDENTIFIER
ruby|Ruby
    0 DEFAULT; 1 ERROR; 2 COMMENT LINE; 3 POD; 4 NUMBER; 5 INSTRUCTION=instre1; 6 STRING; 7
    CHARACTER; 8 CLASS NAME; 9 DEF NAME; 10 OPERATOR; 11 IDENTIFIER; 12 REGEX; 13 GLOBAL; 14 SYMBOL;
    15 MODULE NAME; 16 INSTANCE VAR; 17 CLASS VAR; 18 BACKTICKS; 19 DATA SECTION; 24 STRING Q
bash|Bash
    0 DEFAULT; 1 ERROR; 4 INSTRUCTION WORD=instre1; 3 NUMBER; 5 STRING; 6 CHARACTER; 7 OPERATOR; 8
    IDENTIFIER; 9 SCALAR; 2 COMMENT LINE; 10 PARAM; 11 BACKTICKS; 12 HERE DELIM; 13 HERE Q; 128 USER
    KEYWORDS 1=substyle1; 129 USER KEYWORDS 2=substyle2; 130 USER KEYWORDS 3=substyle3; 131 USER
    KEYWORDS 4=substyle4; 132 USER SCALAR 1=substyle5; 133 USER SCALAR 2=substyle6; 134 USER SCALAR
    3=substyle7; 135 USER SCALAR 4=substyle8
haskell|Haskell
    0 DEFAULT; 1 IDENTIFIER; 2 KEYWORD; 3 NUMBER; 4 STRING; 5 CHARACTER; 6 CLASS; 7 MODULE; 8
    CAPITAL; 9 DATA; 10 IMPORT; 11 OPERATOR; 12 INSTANCE; 13 COMMENT LINE; 14 COMMENT BLOCK; 15
    COMMENT BLOCK2; 16 COMMENT BLOCK3
lua|Lua
    0 DEFAULT; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 8 LITERAL STRING; 9 PREPROCESSOR; 5
    INSTRUCTION WORD=instre1; 4 NUMBER; 6 STRING; 7 CHARACTER; 10 OPERATOR; 13 FUNC1=instre2; 14
    FUNC2=type1; 15 FUNC3=type2; 16 USER KEYWORDS 1=type3; 17 USER KEYWORDS 2=type4; 18 USER
    KEYWORDS 3=type5; 19 USER KEYWORDS 4=type6; 11 IDENTIFIER; 20 LABEL; 128 USER KEYWORDS
    5=substyle1; 129 USER KEYWORDS 6=substyle2; 130 USER KEYWORDS 7=substyle3; 131 USER KEYWORDS
    8=substyle4
yaml|YAML
    0 DEFAULT; 2 IDENTIFIER; 1 COMMENT; 3 INSTRUCTION WORD=instre1; 4 NUMBER; 5 REFERENCE; 6
    DOCUMENT; 7 TEXT; 8 ERROR
props|Properties file
    0 DEFAULT; 1 COMMENT; 2 SECTION; 3 ASSIGNMENT; 4 DEFVAL; 5 KEY
php|PHP
    18 QUESTION MARK; 118 DEFAULT; 119 STRING; 104 COMPLEX VARIABLE; 126 STRING VARIABLE; 120 SIMPLE
    STRING; 121 KEYWORDS=instre1; 122 NUMBER; 123 VARIABLE; 124 COMMENT; 125 COMMENT LINE; 127
    OPERATOR; 213 PREDEFINED=substyle6; 214 FUNCS AND METHODS 1=substyle7; 215 FUNCS AND METHODS
    2=substyle8; 208 USER KEYWORDS 1=substyle1; 209 USER KEYWORDS 2=substyle2; 210 USER KEYWORDS
    3=substyle3; 211 USER KEYWORDS 4=substyle4; 212 USER KEYWORDS 5=substyle5
makefile|Makefile
    0 DEFAULT; 1 COMMENT; 2 PREPROCESSOR; 3 IDENTIFIER; 4 OPERATOR; 5 TARGET; 9 IDEOL
powershell|PowerShell
    0 DEFAULT; 1 COMMENT; 2 STRING; 3 CHARACTER; 4 NUMBER; 5 VARIABLE; 6 OPERATOR; 7 IDENTIFIER; 8
    INSTRUCTION WORD=instre1; 9 CMDLET=instre2; 10 ALIAS=type1; 11 FUNCTION=type2; 12 USER
    KEYWORDS=type3; 13 COMMENT STREAM; 14 HERE STRING; 15 HERE CHARACTER; 16 COMMENT DOC
    KEYWORD=type4
matlab|Matlab
    0 DEFAULT; 1 COMMENT; 2 COMMAND; 3 NUMBER; 4 INSTRUCTION WORD=instre1; 5 STRING; 6 OPERATOR; 7
    IDENTIFIER; 8 DOUBLE QUOTE STRING
nncrontab|nnCron
    0 WHITE SPACE; 1 COMMENT; 2 TASK START/END; 3 SECTION KEYWORDS=instre1; 4 KEYWORDS=instre2; 5
    MODIFICATORS=type1; 6 ASTERISK; 7 NUMBER; 8 DOUBLE QUOTED STRING; 9 ENVIRONMENT VARIABLE; 10
    IDENTIFIER
lisp|LISP
    0 DEFAULT; 1 COMMENT LINE; 2 NUMBER; 3 FUNCTION WORD=instre1; 4 FUNCTION WORD2=instre2; 5
    SYMBOL; 6 STRING; 9 IDENTIFIER; 10 OPERATOR=type1; 11 SPECIAL; 12 COMMENT
pascal|Pascal
    0 DEFAULT; 1 IDENTIFIER; 2 COMMENT; 3 COMMENT LINE; 4 COMMENT DOC; 5 PREPROCESSOR; 6
    PREPROCESSOR2; 7 NUMBER; 8 HEX NUMBER; 9 INSTRUCTION WORD=instre1; 10 STRING; 12 CHARACTER; 13
    OPERATOR; 14 ASM; 15 MULTILINESTRING
r|R
    0 DEFAULT; 1 COMMENT; 2 INSTRUCTION WORD=instre1; 3 BASE WORD=instre2; 4 KEYWORD=type1; 5
    NUMBER; 6 STRING; 7 STRING2; 8 OPERATOR; 9 IDENTIFIER; 10 INFIX; 11 INFIXEOL; 12 BACKTICKS; 13
    RAWSTRING; 14 RAWSTRING2; 15 ESCAPESEQUENCE
registry|Registry
    32 DEFAULT STYLE; 0 DEFAULT; 1 COMMENT; 2 VALUE NAME; 3 STRING; 4 HEX DIGIT; 5 VALUE TYPE; 6
    ADDED KEY; 7 REMOVED KEY; 8 ESCAPED CHARACTERS IN STRINGS; 9 GUID IN KEY PATH; 10 GUID IN
    STRING; 11 PARAMETER; 12 OPERATORS
autoit|AutoIt
    0 DEFAULT; 1 COMMENT LINE; 2 COMMENT; 3 NUMBER; 4 FUNCTION=instre2; 5 INSTRUCTION WORD=instre1;
    6 MACRO=type1; 7 STRING; 8 OPERATOR; 9 VARIABLE; 10 SENT=type2; 11 PREPROCESSOR=type3; 12
    SPECIAL=type4; 13 EXPAND=type5; 14 COMOBJ
vb|VB / VBS
    7 DEFAULT; 1 COMMENT; 2 NUMBER; 3 WORD=instre1; 4 STRING; 5 PREPROCESSOR; 6 OPERATOR; 8 DATE
kix|KiXtart
    31 DEFAULT; 1 COMMENT; 2 STRING; 3 STRING2; 4 NUMBER; 5 VAR; 6 MACRO=instre2; 7 INSTRUCTION
    WORD=instre1; 8 FUNCTION=type1; 9 OPERATOR
latex|LaTeX
    0 WHITE SPACE; 1 COMMAND; 2 TAG OPENING; 3 MATH INLINE; 4 COMMENT; 5 TAG CLOSING; 6 MATH BLOCK;
    7 COMMENT BLOCK; 8 VERBATIM SEGMENT; 9 SHORT COMMAND; 10 SPECIAL CHAR; 11 COMMAND OPTIONAL
    ARGUMENT; 12 SYNTAX ERROR
searchResult|Search result
    1 Search Header; 2 File Header; 3 Line Number; 4 Hit Word; 6 Current line background colour
srec|S-Record
    0 DEFAULT; 1 RECSTART; 2 RECTYPE; 3 RECTYPE_UNKNOWN; 4 BYTECOUNT; 5 BYTECOUNT_WRONG; 6
    NOADDRESS; 7 DATAADDRESS; 8 RECCOUNT; 9 STARTADDRESS; 10 ADDRESSFIELD_UNKNOWN; 12 DATA_ODD; 13
    DATA_EVEN; 14 DATA_UNKNOWN; 15 DATA_EMPTY; 16 CHECKSUM; 17 CHECKSUM_WRONG; 18 GARBAGE
ihex|Intel HEX
    0 DEFAULT; 1 RECSTART; 2 RECTYPE; 3 RECTYPE_UNKNOWN; 4 BYTECOUNT; 5 BYTECOUNT_WRONG; 6
    NOADDRESS; 7 DATAADDRESS; 9 STARTADDRESS; 10 ADDRESSFIELD_UNKNOWN; 11 EXTENDEDADDRESS; 12
    DATA_ODD; 13 DATA_EVEN; 14 DATA_UNKNOWN; 15 DATA_EMPTY; 16 CHECKSUM; 17 CHECKSUM_WRONG; 18
    GARBAGE
tex|TeX
    0 DEFAULT; 1 SPECIAL; 2 GROUP; 3 SYMBOL; 4 COMMAND; 5 TEXT
erlang|Erlang
    0 DEFAULT STYLE; 1 DEFAULT COMMENT; 14 FUNCTION COMMENT; 15 MODULE COMMENT; 16 DOCUMENTATION
    HELPER IN COMMENT=type3; 17 DOCUMENTATION MACRO IN COMMENT=type4; 2 VARIABLE; 3 NUMBER; 5
    STRING; 9 CHARACTER; 10 MACRO; 19 MACRO QUOTED; 11 RECORD; 20 RECORD QUOTED; 7 ATOM; 18 ATOM
    QUOTED; 13 NODE NAME; 21 NODE NAME QUOTED; 4 RESERVED WORDS=instre1; 22 BUILT-IN
    FUNCTIONS=instre2; 8 FUNCTION NAME; 23 MODULE NAME; 24 MODULE ATTRIBUTES=type2; 12
    PREPROCESSOR=type1; 6 OPERATORS; 31 UNKNOWN: ERROR
verilog|Verilog
    0 DEFAULT; 11 IDENTIFIER; 5 INSTRUCTION WORD=instre1; 7 KEYWORD=type1; 10 OPERATOR; 4 NUMBER; 9
    PREPROCESSOR; 6 STRING; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT LINE BANG; 19 USER
vhdl|VHDL
    0 DEFAULT; 1 COMMENT; 2 COMMENT LINE BANG; 15 COMMENT BLOCK; 3 NUMBER; 4 STRING; 7 STRING EOL; 5
    OPERATOR; 6 IDENTIFIER; 8 INSTRUCTION=instre1; 9 STD OPERATOR=instre2; 10 ATTRIBUTE=type1; 11
    STD FUNCTION=type2; 12 STD PACKAGE=type3; 13 STD TYPE=type4; 14 USER DEFINE=type5
nfo|DOS Style
    32 DEFAULT
go|Go
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 19 PREDECLARED
    IDENTIFIERS=instre2; 4 NUMBER; 6 STRING; 20 STRING RAW; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM;
    14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD;
    18 COMMENT DOC KEYWORD ERROR; 23 PREPROCESSOR COMMENT; 24 PREPROCESSOR COMMENT DOC; *user
perl|Perl
    0 DEFAULT; 5 INSTRUCTION WORD=instre1; 4 NUMBER; 10 OPERATOR; 11 IDENTIFIER; 12 SCALAR; 13
    ARRAY; 14 HASH; 15 SYMBOL TABLE; 40 PROTOTYPE; 2 COMMENT LINE; 7 STRING SINGLEQUOTE; 6 STRING
    DOUBLEQUOTE; 20 STRING BACKTICKS; 26 STRING Q; 27 STRING QQ; 28 STRING QX; 29 STRING QR; 30
    STRING QW; 17 REGEX MATCH; 18 REGEX SUBSTITUTION; 44 TRANSLATION; 22 HEREDOC DELIMITER; 23
    HEREDOC SINGLEQUOTE; 24 HEREDOC DOUBLEQUOTE; 25 HEREDOC BACKTICK; 43 VAR IN STRING; 54 VAR IN
    REGEX; 55 VAR IN REGEX SUBSTITUTION; 57 VAR IN BACKTICKS; 61 VAR IN HEREDOC DOUBLEQUOTE; 62 VAR
    IN HEREDOC BACKTICK; 64 VAR IN STRING QQ; 65 VAR IN STRING QX; 66 VAR IN STRING QR; 41 FORMAT
    IDENTIFIER; 42 FORMAT BODY; 21 DATA SECTION; 3 POD; 31 POD VERBATIM; 1 ERROR
swift|Swift
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING;
    7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15
    COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23 PREPROCESSOR COMMENT;
    24 PREPROCESSOR COMMENT DOC; *user
objc|Objective-C
    19 DIRECTIVE=instre2; 11 DEFAULT; 20 QUALIFIER=type2; 9 PREPROCESSOR; 5 INSTRUCTION
    WORD=instre1; 16 TYPE WORD=type1; 4 NUMBER; 6 STRING; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14
    REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18
    COMMENT DOC KEYWORD ERROR
asm|Assembly
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 STRING; 4 OPERATOR; 5 IDENTIFIER; 6 CPU INSTRUCTION=instre1; 7
    MATH INSTRUCTION=instre2; 8 REGISTER=type1; 9 DIRECTIVE=type2; 10 DIRECTIVE OPERAND=type3; 11
    COMMENT BLOCK; 12 CHARACTER; 14 EXT INSTRUCTION=type4
fortran|Fortran (free form)
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 STRING; 4 STRING2; 6 OPERATOR; 7 IDENTIFIER; 8 INSTRUCTION
    WORD=instre1; 9 FUNCTION1=instre2; 10 FUNCTION2=type1; 11 PREPROCESSOR; 12 OPERATOR2; 13 LABEL;
    14 CONTINUATION
coffeescript|CoffeeScript
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=instre2; 4 NUMBER; 6
    STRING; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT
    DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 19 PREDEFINED
    CONSTANT=type2; 22 COMMENT BLOCK; 23 VERBOSE REGEX; 24 VERBOSE REGEX COMMENT
nsis|NSIS
    0 DEFAULT; 1 COMMENT LINE; 2 STRING DOUBLE QUOTE; 3 STRING LEFT QUOTE; 4 STRING RIGHT QUOTE; 5
    FUNCTION=instre1; 6 VARIABLE=instre2; 7 LABEL=type1; 8 USER DEFINED=type2; 9 SECTION; 10
    SUBSECTION; 11 IF DEFINE; 12 MACRO; 13 STRING VAR; 14 NUMBER; 15 SECTION GROUP; 16 PAGE EX; 17
    FUNCTION DEFINITIONS; 18 COMMENT
actionscript|ActionScript
    11 DEFAULT; 20 FUNCTION=type2; 9 PREPROCESSOR; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD=type1; 4
    NUMBER; 6 STRING; 7 CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3
    COMMENT DOC; 15 COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23
    PREPROCESSOR COMMENT; 24 PREPROCESSOR COMMENT DOC; *user
ada|ADA
    0 DEFAULT; 1 INSTRUCTION WORD=instre1; 2 IDENTIFIER; 3 NUMBER; 4 DELIMITER; 5 CHARACTER; 7
    STRING; 9 LABEL; 10 COMMENT LINE; 11 ILLEGAL
asn1|ASN.1
    0 DEFAULT; 1 COMMENT; 2 IDENTIFIERS; 3 DOUBLE QUOTED STRING; 4 NUMERIC OID DEFINITION; 5 NON OID
    NUMBERS; 6 KEYWORDS=instre1; 7 ATTRIBUTES=instre2; 8 DESCRIPTORS=type1; 9 TYPES=type2; 10
    OPERATORS
asp|ASP
    81 DEFAULT; 82 COMMENT LINE; 83 NUMBER; 84 WORD=instre1; 85 STRING; 86 IDENTIFIER; 15 ASP
    SYMBOL; 16 SCRIPT TYPE; 216 USER KEYWORDS 1=substyle1; 217 USER KEYWORDS 2=substyle2; 218 USER
    KEYWORDS 3=substyle3; 219 USER KEYWORDS 4=substyle4; 220 USER KEYWORDS 5=substyle5; 221 USER
    KEYWORDS 6=substyle6; 222 USER KEYWORDS 7=substyle7; 223 USER KEYWORDS 8=substyle8
avs|AviSynth
    32 DEFAULT; 0 WHITE SPACE; 1 COMMENT: /* */; 2 COMMENT: [* *]; 3 LINE COMMENT: #; 4 NUMBER; 5
    OPERATORS; 6 IDENTIFIERS; 7 DOUBLE QUOTED STRING; 8 STRING WITH THREE DOUBLE QUOTES; 9
    KEYWORD=instre1; 10 FILTER=instre2; 11 PLUGIN=type1; 12 FUNCTION=type2; 13 CLIP
    PROPERTIES=type3; 14 USER DEFINED=type4
baanc|BaanC
    0 DEFAULT; 1 COMMENT; 2 COMMENT DOC; 3 NUMBER; 4 KEYWORDS=instre1; 5 STRING; 6 PREPROCESSOR; 7
    OPERATOR; 8 IDENTIFIER; 9 STRING EOL NC; 10 FUNCTIONS=instre2; 11 FUNCTIONS ABRIDGED=type1; 12
    SUB SECTIONS=type2; 13 MAIN SECTIONS=type3; 14 PREDEFINED VARIABLE=type4; 15 PREDEFINED
    ATTRIBUTES=type5; 16 ENUM DOMAINS=type6; 17 USER DEFINED=type7; 18 TABLE DEFINITIONS; 19 TABLE
    SQL; 20 DLL FUNCTIONS; 21 DOMAIN DEFINITIONS; 22 FUNCTION DEFINITIONS; 23 OBJECT DEFINITIONS; 24
    PREPROC DEFINITIONS
blitzbasic|BlitzBasic
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 KEYWORD1=instre1; 4 STRING; 6 OPERATOR; 7 IDENTIFIER; 10
    KEYWORD2=instre2; 11 KEYWORD3=type1; 12 KEYWORD4=type2; 15 LABEL; 16 ERROR; 17 HEXNUMBER; 18
    BINNUMBER
caml|Caml
    0 DEFAULT; 1 IDENTIFIER; 2 TAGNAME; 3 INSTRUCTION WORD=instre1; 4 BUILIN FUNC & TYPE=instre2; 5
    TYPE=type1; 6 LINENUM; 7 OPERATOR; 8 NUMBER; 9 CHARACTER; 11 STRING; 12 COMMENT; 13 COMMENT
    LINE; 14 COMMENT DOC; 15 COMMENT LINE DOC
cobol|COBOL
    9 PREPROCESSOR; 11 DEFAULT; 5 DECLARATION=instre1; 16 INSTRUCTION WORD=instre2; 8 KEYWORD=type1;
    4 NUMBER; 6 STRING; 7 CHARACTER; 10 OPERATOR; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15
    COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR
csound|Csound
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 OPERATOR; 4 INSTR; 5 IDENTIFIER; 6 OPCODE=instre1; 7 HEADER
    STATEMENT=instre2; 8 USER KEYWORDS=type1; 9 COMMENT BLOCK; 10 PARAMETER; 11 A-RATE VARIABLE; 12
    K-RATE VARIABLE; 13 I-RATE VARIABLE; 14 GLOBAL VARIABLE; 15 END OF LINE WHERE STRING IS NOT
    CLOSED
d|D
    0 DEFAULT; 14 IDENTIFIER; 6 INSTRUCTION WORD=instre1; 7 KEYWORD1=instre2; 8 KEYWORD2=type1; 9
    KEYWORD3=type2; 20 KEYWORD4=type3; 21 KEYWORD5=type4; 22 KEYWORD6=type5; 5 NUMBER; 10 STRING; 12
    CHARACTER; 13 OPERATOR; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 4 COMMENT NESTED; 15 COMMENT
    LINE DOC; 16 COMMENT DOC KEYWORD; 17 COMMENT DOC KEYWORD ERROR; 18 STRING B; 19 STRING R
errorlist|ErrorList
    0 DEFAULT STYLE; 1 PYTHON Error; 2 GCC Error; 3 MS Error; 4 CMD Error; 5 BORLAND Error; 6 PERL
    Error; 7 NET Error; 8 LUA Error; 9 CTAG Error; 10 DIFF Changed; 11 DIFF Addition; 12 DIFF
    Deletion; 13 DIFF Message; 14 PHP Error; 15 ELF Error; 16 IFC Error; 17 IFORT Error; 18 ABSF
    Error; 19 TIDY Error; 20 JAVA Stack Error; 21 VALUE Error; 22 GCC Included-From Error; 23 Escape
    Sequence; 24 Unknown Escape Sequence; 25 GCC Excerpt Error; 26 BASH Error; 40 ANSI COLOR BLACK;
    41 ANSI COLOR RED; 42 ANSI COLOR GREEN; 43 ANSI COLOR BROWN; 44 ANSI COLOR BLUE; 45 ANSI COLOR
    MAGENTA; 46 ANSI COLOR CYAN; 47 ANSI COLOR GRAY; 48 ANSI COLOR DARK GRAY; 49 ANSI COLOR BRIGHT
    RED; 50 ANSI COLOR BRIGHT GREEN; 51 ANSI COLOR YELLOW; 52 ANSI COLOR BRIGHT BLUE; 53 ANSI COLOR
    BRIGHT MAGENTA; 54 ANSI COLOR BRIGHT CYAN; 55 ANSI COLOR WHITE
escseq|Escape Sequence (ANSI)
    0 DEFAULT on DEFAULT; 1 BLACK on DEFAULT; 2 RED on DEFAULT; 3 GREEN on DEFAULT; 4 YELLOW on
    DEFAULT; 5 BLUE on DEFAULT; 6 MAGENTA on DEFAULT; 7 CYAN on DEFAULT; 8 WHITE on DEFAULT; 9
    DEFAULT on BLACK; 10 BLACK on BLACK; 11 RED on BLACK; 12 GREEN on BLACK; 13 YELLOW on BLACK; 14
    BLUE on BLACK; 15 MAGENTA on BLACK; 16 CYAN on BLACK; 17 WHITE on BLACK; 18 DEFAULT on RED; 19
    BLACK on RED; 20 RED on RED; 21 GREEN on RED; 22 YELLOW on RED; 23 BLUE on RED; 24 MAGENTA on
    RED; 25 CYAN on RED; 26 WHITE on RED; 27 DEFAULT on GREEN; 28 BLACK on GREEN; 29 RED on GREEN;
    30 GREEN on GREEN; 40 YELLOW on GREEN; 41 BLUE on GREEN; 42 MAGENTA on GREEN; 43 CYAN on GREEN;
    44 WHITE on GREEN; 45 DEFAULT on YELLOW; 46 BLACK on YELLOW; 47 RED on YELLOW; 48 GREEN on
    YELLOW; 49 YELLOW on YELLOW; 50 BLUE on YELLOW; 51 MAGENTA on YELLOW; 52 CYAN on YELLOW; 53
    WHITE on YELLOW; 54 DEFAULT on BLUE; 55 BLACK on BLUE; 56 RED on BLUE; 57 GREEN on BLUE; 58
    YELLOW on BLUE; 59 BLUE on BLUE; 60 MAGENTA on BLUE; 61 CYAN on BLUE; 62 WHITE on BLUE; 63
    DEFAULT on MAGENTA; 64 BLACK on MAGENTA; 65 RED on MAGENTA; 66 GREEN on MAGENTA; 67 YELLOW on
    MAGENTA; 68 BLUE on MAGENTA; 69 MAGENTA on MAGENTA; 70 CYAN on MAGENTA; 71 WHITE on MAGENTA; 72
    DEFAULT on CYAN; 73 BLACK on CYAN; 74 RED on CYAN; 75 GREEN on CYAN; 76 YELLOW on CYAN; 77 BLUE
    on CYAN; 78 MAGENTA on CYAN; 79 CYAN on CYAN; 80 WHITE on CYAN; 81 DEFAULT on WHITE; 82 BLACK on
    WHITE; 83 RED on WHITE; 84 GREEN on WHITE; 85 YELLOW on WHITE; 86 BLUE on WHITE; 87 MAGENTA on
    WHITE; 88 CYAN on WHITE; 89 WHITE on WHITE; 090 BOLD DEFAULT on DEFAULT; 091 BOLD BLACK on
    DEFAULT; 092 BOLD RED on DEFAULT; 093 BOLD GREEN on DEFAULT; 094 BOLD YELLOW on DEFAULT; 095
    BOLD BLUE on DEFAULT; 096 BOLD MAGENTA on DEFAULT; 097 BOLD CYAN on DEFAULT; 098 BOLD WHITE on
    DEFAULT; 099 BOLD DEFAULT on BLACK; 100 BOLD BLACK on BLACK; 101 BOLD RED on BLACK; 102 BOLD
    GREEN on BLACK; 103 BOLD YELLOW on BLACK; 104 BOLD BLUE on BLACK; 105 BOLD MAGENTA on BLACK; 106
    BOLD CYAN on BLACK; 107 BOLD WHITE on BLACK; 108 BOLD DEFAULT on RED; 109 BOLD BLACK on RED; 110
    BOLD RED on RED; 111 BOLD GREEN on RED; 112 BOLD YELLOW on RED; 113 BOLD BLUE on RED; 114 BOLD
    MAGENTA on RED; 115 BOLD CYAN on RED; 116 BOLD WHITE on RED; 117 BOLD DEFAULT on GREEN; 118 BOLD
    BLACK on GREEN; 119 BOLD RED on GREEN; 120 BOLD GREEN on GREEN; 121 BOLD YELLOW on GREEN; 122
    BOLD BLUE on GREEN; 123 BOLD MAGENTA on GREEN; 124 BOLD CYAN on GREEN; 125 BOLD WHITE on GREEN;
    126 BOLD DEFAULT on YELLOW; 127 BOLD BLACK on YELLOW; 128 BOLD RED on YELLOW; 129 BOLD GREEN on
    YELLOW; 130 BOLD YELLOW on YELLOW; 131 BOLD BLUE on YELLOW; 132 BOLD MAGENTA on YELLOW; 133 BOLD
    CYAN on YELLOW; 134 BOLD WHITE on YELLOW; 135 BOLD DEFAULT on BLUE; 136 BOLD BLACK on BLUE; 137
    BOLD RED on BLUE; 138 BOLD GREEN on BLUE; 139 BOLD YELLOW on BLUE; 140 BOLD BLUE on BLUE; 141
    BOLD MAGENTA on BLUE; 142 BOLD CYAN on BLUE; 143 BOLD WHITE on BLUE; 144 BOLD DEFAULT on
    MAGENTA; 145 BOLD BLACK on MAGENTA; 146 BOLD RED on MAGENTA; 147 BOLD GREEN on MAGENTA; 148 BOLD
    YELLOW on MAGENTA; 149 BOLD BLUE on MAGENTA; 150 BOLD MAGENTA on MAGENTA; 151 BOLD CYAN on
    MAGENTA; 152 BOLD WHITE on MAGENTA; 153 BOLD DEFAULT on CYAN; 154 BOLD BLACK on CYAN; 155 BOLD
    RED on CYAN; 156 BOLD GREEN on CYAN; 157 BOLD YELLOW on CYAN; 158 BOLD BLUE on CYAN; 159 BOLD
    MAGENTA on CYAN; 160 BOLD CYAN on CYAN; 161 BOLD WHITE on CYAN; 162 BOLD DEFAULT on WHITE; 163
    BOLD BLACK on WHITE; 164 BOLD RED on WHITE; 165 BOLD GREEN on WHITE; 166 BOLD YELLOW on WHITE;
    167 BOLD BLUE on WHITE; 168 BOLD MAGENTA on WHITE; 169 BOLD CYAN on WHITE; 170 BOLD WHITE on
    WHITE; 171 Sequence Identifier; 172 Sequence Unknown
escript|eScript
    0 DEFAULT; 1 COMMENT; 2 LINE COMMENT; 3 DOC COMMENT; 4 NUMBER; 5 KEYWORD=instre1; 6 DOUBLE
    QUOTED STRING; 7 OPERATORS; 8 IDENTIFIERS; 9 BRACES; 10 KEYWORDS2=instre2; 11 KEYWORDS3=type1
forth|Forth
    0 WHITESPACE; 1 COMMENT; 2 ML COMMENT; 3 IDENTIFIER; 4 CONTROL=instre1; 5 KEYWORDS=instre2; 6
    DEFWORDS=type1; 7 PREWORD1=type2; 8 PREWORD2=type3; 9 NUMBER; 10 DOUBLE QUOTED STRING=type4; 11
    LOCALE
fortran77|Fortran (fixed form)
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 STRING; 4 STRING2; 6 OPERATOR; 7 IDENTIFIER; 8 INSTRUCTION
    WORD=instre1; 9 FUNCTION1=instre2; 10 FUNCTION2=type1; 11 PREPROCESSOR; 12 OPERATOR2; 13 LABEL;
    14 CONTINUATION
freebasic|FreeBASIC
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 KEYWORD1=instre1; 4 STRING; 5 PREPROCESSOR; 6 OPERATOR; 7
    IDENTIFIER; 10 KEYWORD2=instre2; 11 KEYWORD3=type1; 12 KEYWORD4=type2; 15 LABEL; 16 ERROR; 17
    HEXNUMBER; 18 BINNUMBER
gdscript|GDScript
    0 DEFAULT; 1 COMMENT LINE; 2 NUMBER; 3 STRING; 4 CHARACTER; 5 WORD=instre1; 6 TRIPLE; 7 TRIPLE
    DOUBLE; 8 CLASS NAME; 9 FUNC NAME; 10 OPERATOR; 11 IDENTIFIER; 12 COMMENT BLOCK; 13 STRING EOL;
    14 WORD2=instre2; 15 ANNOTATION; 16 NODEPATH; *user
gui4cli|Gui4Cli
    0 DEFAULT; 1 COMMENT LINE; 2 COMMENT; 3 GLOBAL=instre1; 4 EVENT=instre2; 5 ATTRIBUTE=type1; 6
    CONTROL=type2; 7 COMMAND=type3; 8 STRING; 9 OPERATOR
hollywood|Hollywood
    0 DEFAULT; 1 COMMENT; 2 COMMENT BLOCK; 3 NUMBER; 4 KEYWORD=instre1; 5 CORE API=instre2; 6 PLUGIN
    API=type1; 7 PLUGIN METHOD=type2; 8 STRING; 9 STRING BLOCK; 10 PREPROCESSOR; 11 OPERATOR; 12
    IDENTIFIER; 13 CONSTANT; 14 HEXNUMBER
mssql|MS T-SQL
    9 STATEMENT=instre1; 10 DATA TYPE=instre2; 11 SYSTEM TABLE=type1; 12 GLOBAL=type2; 13
    FUNCTION=type3; 14 SYSTEM STORED PROC=type4; 1 COMMENT; 2 COMMENT LINE; 3 NUMBER; 4 STRING; 5
    OPERATOR; 6 IDENTIFIER; 7 VARIABLE; 8 COL NAME; 16 COL NAME IN []'s
mmixal|MMIXAL
    0 DIVSION OF LEADING WHITESPACE IN LINE; 1 COMMENT; 2 LABEL; 3 OPCODE; 4 DIVISION BETWEEN LABEL
    AND OPCODE; 5 VALID OPCODE=instre1; 6 UNKNOWN OPCODE; 7 DIVISION BETWEEN OPCODE AND OPERANDS; 8
    DIVISION OF OPERANDS; 9 NUMBER; 10 REFERENCE (TO A LABEL); 11 CHAR; 12 STRING; 13
    REGISTER=instre2; 14 HEXADECIMAL NUMBER; 15 OPERATOR; 16 SYMBOL=type1; 17 COMMENT OTHERWISE
nim|Nim
    0 WHITE SPACE; 1 COMMENT; 2 NUMBER; 3 STRING; 4 SINGLE QUOTED STRING; 5 KEYWORD=instre1; 6
    TRIPLE QUOTES; 7 TRIPLE DOUBLE QUOTES; 8 CLASS NAME DEFINITION; 9 FUNCTION OR METHOD NAME
    DEFINITION; 10 OPERATORS; 11 IDENTIFIERS; 12 COMMENT-BLOCKS; 13 END OF LINE WHERE STRING IS NOT
    CLOSED; 14 HIGHLIGHTED IDENTIFIERS; 15 DECORATORS
oscript|OScript
    0 DEFAULT TEXT STYLE; 1 SINGLE-LINE COMMENT; 2 MULTI-LINE COMMENT; 3 #IFDEF DOC AND #ENDIF; 4
    PREPROCESSOR DIRECTIVE; 5 NUMBER; 6 STRING SINGLE QUOTES; 7 STRING DOUBLE QUOTES; 8 CONSTANT
    LITERAL=instre2; 9 IDENTIFIER; 10 SERVER-GLOBAL VARIABLE (PREFIXED BY $); 11 LANGUAGE NATIVE
    KEYWORD OR RESERVED WORD=instre1; 12 OPERATOR; EITHER SYMBOLIC OR LITERAL=type1; 13 LABEL TO
    JUMP TO WITH THE GOTO STATEMENT; 14 TYPE=type2; 15 FUNCTION=type3; 16 STATIC BUILT-IN
    OBJECT=type4; 17 OBJECT PROPERTY; 18 OBJECT METHOD
postscript|Postscript
    0 DEFAULT; 1 COMMENT; 2 DSC COMMENT; 3 DSC VALUE; 4 NUMBER; 5 Name; 6 INSTRUCTION=instre1; 7
    LITERAL; 8 IMMEVAL; 9 PAREN ARRAY; 10 PAREN DICT; 11 PAREN PROC; 12 TEXT; 13 HEX STRING; 14
    BASE85 STRING; 15 BAD STRING CHAR
purebasic|PureBasic
    0 DEFAULT; 1 COMMENT; 2 NUMBER; 3 KEYWORD1=instre1; 4 STRING; 6 OPERATOR; 7 IDENTIFIER; 10
    KEYWORD2=instre2; 11 KEYWORD3=type1; 12 KEYWORD4=type2; 13 CONSTANT; 15 LABEL; 16 ERROR; 17
    HEXNUMBER; 18 BINNUMBER
raku|Raku
    0 DEFAULT; 1 ERROR; 2 COMMENT LINE; 3 COMMENT EMBED; 4 POD; 5 CHARACTER; 6 HEREDOC Q; 7 HEREDOC
    QQ; 8 STRING; 9 STRING Q; 10 STRING QQ; 11 STRING Q_LANG; 12 STRING VAR; 13 REGEX; 14 REGEX VAR;
    15 ADVERB=type5; 16 NUMBER; 17 PREPROCESSOR; 18 OPERATOR; 19 INSTRUCTION WORD=instre1; 20
    FUNCTION=instre2; 21 IDENTIFIER; 22 TYPEDEF=type1; 23 MU; 24 POSITIONAL; 25 ASSOCIATIVE; 26
    CALLABLE; 27 GRAMMAR; 28 CLASS
rc|Resource file
    9 PREPROCESSOR; 11 DEFAULT; 5 INSTRUCTION WORD=instre1; 16 TYPE WORD; 4 NUMBER; 6 STRING; 7
    CHARACTER; 10 OPERATOR; 13 VERBATIM; 14 REGEX; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT DOC; 15
    COMMENT LINE DOC; 17 COMMENT DOC KEYWORD; 18 COMMENT DOC KEYWORD ERROR; 23 PREPROCESSOR COMMENT;
    24 PREPROCESSOR COMMENT DOC; *user
rebol|REBOL
    32 DEFAULT; 0 ANY OTHER TEXT; 1 LINE COMMENT; 2 BLOCK COMMENT; 3 PREFACE; 4 OPERATORS; 5
    CHARACTERS; 6 STRING WITH QUOTES; 7 STRING WITH BRACES; 8 NUMBER; 9 PAIR ( 800X600 ); 10 TUPLE (
    127.0.0.1 ); 11 BINARY ( 16#{1A803F59} ); 12 MONEY; 13 ISSUE { #123-CD-456 }; 14 TAG { <TITLE
    HEIGHT=100> }; 15 FILE { %/C/WINNT/SOME.DLL }; 16 EMAIL { JOE@MAIL.DOM }; 17 URL {
    FTP://THERE.DOM }; 18 DATE { 17-FEB-2004 1/3/99 }; 19 TIME { 12:30 11:22:59 01:59:59.123 }; 20
    IDENTIFIERS; 21 KEYWORD (ALL)=instre1; 22 KEYWORD (TEST FUNCTIONS)=instre2; 23 KEYWORD
    (DATATYPES)=type1; 24 KEYWORD 4=type2; 25 KEYWORD 5=type3; 26 KEYWORD 6=type4; 27 KEYWORD
    7=type5
sas|SAS
    0 DEFAULT; 1 COMMENT; 2 COMMENT LINE; 3 COMMENT BLOCK; 4 NUMBER; 5 OPERATOR; 6 IDENTIFIER; 7
    STRING; 11 MACRO; 12 MACRO KEYWORD=instre1; 14 MACRO FUNCTION=type1; 13 FUNCTION=instre2; 15
    STATEMENT=type2
scheme|Scheme
    0 DEFAULT; 1 COMMENT LINE; 2 NUMBER; 3 FUNCTION WORD=instre1; 4 FUNCTION WORD2=instre2; 5
    SYMBOL; 6 STRING; 9 IDENTIFIER; 10 OPERATOR=type1; 11 SPECIAL; 12 COMMENT
smalltalk|Smalltalk
    0 DEFAULT; 1 STRING; 2 NUMBER; 3 COMMENT; 4 SYMBOL; 5 BINARY; 6 BOOL; 7 SELF; 8 SUPER; 9 NIL; 10
    GLOBAL; 11 RETURN; 12 SPECIAL; 13 KWS END; 14 ASSIGN; 15 CHARACTER; 16 SPECIAL SELECTOR
spice|SPICE
    0 DEFAULT; 1 IDENTIFIERS; 2 KEYWORD=instre1; 3 KEYWORD2=instre2; 4 KEYWORD3=type1; 5 NUMBER; 6
    OPERATORS (DELIMITERS); 7 VALUE; 8 COMMENT
tehex|Tektronix extended HEX
    0 DEFAULT; 1 RECSTART; 2 RECTYPE; 3 RECTYPE_UNKNOWN; 4 BYTECOUNT; 5 BYTECOUNT_WRONG; 7
    DATAADDRESS; 9 STARTADDRESS; 10 ADDRESSFIELD_UNKNOWN; 12 DATA_ODD; 13 DATA_EVEN; 16 CHECKSUM; 17
    CHECKSUM_WRONG; 18 GARBAGE
txt2tags|txt2tags
    0 DEFAULT; 1 SPECIAL; 2 STRONG; 3 STRONG 2 (NOT USED); 4 EM1 (ITALIC); 5 EM2 (UNDERLINE); 6 H1;
    7 H2; 8 H3; 9 H4; 10 H5; 11 H6; 12 PRECHAR (NOT USED); 13 ULIST; 14 OLIST; 15 BLOCKQUOTE; 16
    STRIKEOUT; 17 HRULE; 18 LINK; 19 CODE; 20 CODE2; 21 CODEBLOCK; 22 COMMENT; 23 OPTION; 24
    PREPROC; 25 POSTPROC
visualprolog|Visual Prolog
    0 DEFAULT; 1 MAJOR=instre1; 2 MINOR=instre2; 3 DIRECTIVE=type1; 4 COMMENT BLOCK; 5 COMMENT LINE;
    6 COMMENT KEY=type2; 7 COMMENT KEY ERROR; 8 IDENTIFIER; 9 VARIABLE; 10 ANONYMOUS; 11 NUMBER; 12
    OPERATOR; 13 CHARACTER; 14 CHARACTER TOO MANY; 15 CHARACTER ESCAPE ERROR; 16 STRING; 17 STRING
    ESCAPE; 18 STRING ESCAPE ERROR; 19 STRING EOL OPEN; 20 STRING VERBATIM; 21 STRING VERBATIM
    SPECIAL; 22 STRING VERBATIM EOL
"""

USER_KEYWORDS = "; ".join(f"{128 + i} USER KEYWORDS {i + 1}=substyle{i + 1}" for i in range(8))


def lexers():
    """[(name, desc, [(style_id, style_name, keyword_class | None)])]"""
    out = []
    for line in LEXERS.strip("\n").splitlines():
        if not line.startswith(" "):
            name, desc = line.split("|")
            out.append((name, desc, []))
            continue
        chunk = out[-1][2]
        chunk.append(line.strip())
    parsed = []
    for name, desc, chunks in out:
        styles = []
        # "; " separates styles, except inside a name (OScript has one): split only before an id
        for item in re.split(r"; (?=\d+ )", " ".join(chunks).replace("*user", USER_KEYWORDS)):
            sid, rest = item.split(" ", 1)
            m = re.fullmatch(r"(.+)=((?:instre|type|substyle)\d)", rest)
            sname, kw = m.groups() if m else (rest, None)
            styles.append((sid, sname, kw))
        parsed.append((name, desc, styles))
    return parsed


# Where the generic name rules below would guess wrong: (lexer, style) → role.
OVERRIDES = {
    ("cmake", "COMMAND"): "function", ("cmake", "STRING VARIABLE"): "string.escape",
    ("php", "COMPLEX VARIABLE"): "string.escape",
    ("cmake", "USER DEFINED"): "constant",
    ("cmake", "WHILEDEF"): "keyword", ("cmake", "FOREACHDEF"): "keyword",
    ("cmake", "IFDEF"): "keyword", ("cmake", "MACRODEF"): "keyword",
    ("diff", "COMMAND"): "keyword", ("diff", "HEADER"): "diff_header", ("diff", "POSITION"): "diff_position",
    ("diff", "DELETED"): "deleted", ("diff", "ADDED"): "added",
    ("rust", "KEYWORDS 2"): "keyword", ("rust", "KEYWORDS 3"): "type.builtin",
    ("rust", "KEYWORDS 4"): "type", ("rust", "KEYWORDS 5"): "type", ("rust", "KEYWORDS 6"): "type",
    ("rust", "KEYWORDS 7"): "type", ("rust", "LIFETIME"): "decorator",
    ("xml", "XML START"): "preproc", ("xml", "XML END"): "preproc",
    ("xml", "SGML COMMAND"): "preproc", ("html", "SGML COMMAND"): "preproc",
    ("xml", "TAG END"): "tag", ("html", "TAG END"): "tag",
    ("html", "VALUE"): "string",
    ("css", "TAG"): "tag", ("css", "CLASS"): "attribute", ("css", "ID"): "attribute",
    ("css", "PSEUDOCLASS"): "decorator", ("css", "UNKNOWN PSEUDOCLASS"): "decorator",
    ("css", "PSEUDOELEMENT"): "decorator", ("css", "LEGACY PSEUDOELEMENT"): "decorator",
    ("css", "IDENTIFIER"): "property", ("css", "UNKNOWN IDENTIFIER"): "property",
    ("css", "VALUE"): "constant", ("css", "IMPORTANT"): "keyword", ("css", "DIRECTIVE"): "keyword",
    ("css", "ATTRIBUTE"): "attribute", ("css", "MEDIA"): "keyword", ("css", "VARIABLE"): "property",
    ("sql", "USER1"): "function.builtin", ("sql", "KEYWORD2"): "type", ("sql", "Q OPERATOR"): "keyword",
    ("json", "PROPERTY NAME"): "key", ("json", "KEYWORD"): "constant", ("json", "LD KEYWORD"): "keyword",
    ("json", "URI"): "link", ("json", "COMPACT IRI"): "link",
    ("javascript", "WORD"): "variable",
    ("javascript.js", "WINDOW INSTRUCTION"): "variable.builtin",
    ("typescript", "WINDOW INSTRUCTION"): "variable.builtin",
    ("tcl", "MODIFIER"): "keyword", ("tcl", "EXPAND"): "keyword", ("tcl", "TK KEYWORD"): "function.builtin",
    ("tcl", "TK COMMAND"): "function", ("tcl", "SUB BRACE"): "punctuation", ("tcl", "SUBSTITUTION"): "string.escape",
    ("tcl", "WORD IN QUOTE"): "string", ("tcl", "IN QUOTE"): "string",
    ("toml", "TABLE"): "section", ("toml", "KEY"): "key", ("toml", "KEYWORD"): "boolean",
    ("python", "ATTRIBUTE"): "property", ("python", "BUILTINS"): "function.builtin",
    ("batch", "LABEL"): "decorator", ("batch", "HIDE SYMBOL"): "operator", ("batch", "COMMAND"): "function",
    ("batch", "AFTER LABEL"): "comment",
    ("ini", "SECTION"): "section", ("ini", "ASSIGNMENT"): "operator", ("ini", "DEFVAL"): "constant",
    ("ini", "KEY"): "key",
    ("props", "SECTION"): "section", ("props", "ASSIGNMENT"): "operator", ("props", "DEFVAL"): "constant",
    ("props", "KEY"): "key",
    ("inno", "SECTION"): "section", ("inno", "PARAMETER"): "parameter", ("inno", "KEYWORD USER"): "u1",
    ("ruby", "INSTRUCTION"): "keyword", ("ruby", "GLOBAL"): "variable.builtin", ("ruby", "SYMBOL"): "constant",
    ("ruby", "INSTANCE VAR"): "property", ("ruby", "CLASS VAR"): "property", ("ruby", "DATA SECTION"): "comment",
    ("bash", "SCALAR"): "variable.builtin", ("bash", "PARAM"): "string.escape",
    ("bash", "HERE DELIM"): "keyword", ("bash", "HERE Q"): "string", ("bash", "BACKTICKS"): "string.escape",
    ("haskell", "CLASS"): "type", ("haskell", "MODULE"): "namespace", ("haskell", "CAPITAL"): "type",
    ("haskell", "DATA"): "storage", ("haskell", "IMPORT"): "keyword", ("haskell", "INSTANCE"): "keyword",
    ("lua", "PREPROCESSOR"): "preproc", ("lua", "FUNC1"): "function.builtin", ("lua", "FUNC2"): "function.builtin",
    ("lua", "FUNC3"): "function.builtin", ("lua", "LABEL"): "decorator",
    ("yaml", "IDENTIFIER"): "key", ("yaml", "INSTRUCTION WORD"): "constant", ("yaml", "REFERENCE"): "decorator",
    ("yaml", "DOCUMENT"): "operator", ("yaml", "TEXT"): "string",
    ("php", "QUESTION MARK"): "preproc", ("php", "SIMPLE STRING"): "string", ("php", "STRING VARIABLE"): "string.escape",
    ("php", "PREDEFINED"): "variable.builtin", ("php", "FUNCS AND METHODS 1"): "function.builtin",
    ("php", "FUNCS AND METHODS 2"): "function.builtin",
    ("makefile", "PREPROCESSOR"): "preproc", ("makefile", "TARGET"): "function", ("makefile", "IDEOL"): "invalid",
    ("powershell", "CMDLET"): "function.builtin", ("powershell", "ALIAS"): "function",
    ("powershell", "FUNCTION"): "function", ("powershell", "USER KEYWORDS"): "u1",
    ("powershell", "COMMENT DOC KEYWORD"): "doc_keyword",
    ("matlab", "COMMAND"): "function",
    ("nncrontab", "TASK START/END"): "keyword", ("nncrontab", "SECTION KEYWORDS"): "section",
    ("nncrontab", "MODIFICATORS"): "storage", ("nncrontab", "ASTERISK"): "operator",
    ("lisp", "FUNCTION WORD"): "keyword", ("lisp", "FUNCTION WORD2"): "function.builtin",
    ("lisp", "SYMBOL"): "constant", ("lisp", "OPERATOR"): "operator", ("lisp", "SPECIAL"): "decorator",
    ("pascal", "PREPROCESSOR2"): "preproc", ("pascal", "ASM"): "string.escape",
    ("r", "BASE WORD"): "function.builtin", ("r", "KEYWORD"): "function", ("r", "INFIX"): "operator",
    ("r", "INFIXEOL"): "invalid", ("r", "BACKTICKS"): "variable",
    ("registry", "DEFAULT STYLE"): "default", ("registry", "VALUE NAME"): "key", ("registry", "VALUE TYPE"): "type",
    ("registry", "ADDED KEY"): "section", ("registry", "REMOVED KEY"): "deleted",
    ("registry", "GUID IN KEY PATH"): "constant", ("registry", "GUID IN STRING"): "constant",
    ("registry", "PARAMETER"): "parameter", ("registry", "HEX DIGIT"): "number",
    ("autoit", "MACRO"): "variable.builtin", ("autoit", "SENT"): "string.escape", ("autoit", "SPECIAL"): "decorator",
    ("autoit", "EXPAND"): "keyword", ("autoit", "COMOBJ"): "type",
    ("vb", "WORD"): "keyword", ("vb", "DATE"): "number",
    ("kix", "VAR"): "variable", ("kix", "MACRO"): "variable.builtin",
    ("latex", "COMMAND"): "keyword", ("latex", "SHORT COMMAND"): "keyword", ("latex", "TAG OPENING"): "tag",
    ("latex", "TAG CLOSING"): "tag", ("latex", "MATH INLINE"): "preproc", ("latex", "MATH BLOCK"): "preproc",
    ("latex", "VERBATIM SEGMENT"): "code", ("latex", "COMMAND OPTIONAL ARGUMENT"): "parameter",
    ("latex", "SPECIAL CHAR"): "string.escape", ("latex", "WHITE SPACE"): "default",
    ("tex", "SPECIAL"): "string.escape", ("tex", "GROUP"): "punctuation", ("tex", "SYMBOL"): "operator",
    ("tex", "COMMAND"): "keyword", ("tex", "TEXT"): "default",
    ("searchResult", "Search Header"): "search_header", ("searchResult", "File Header"): "file_header",
    ("searchResult", "Line Number"): "line_number", ("searchResult", "Hit Word"): "hit_word",
    ("searchResult", "Current line background colour"): "current_line",
    ("erlang", "DEFAULT STYLE"): "default", ("erlang", "MACRO"): "preproc", ("erlang", "MACRO QUOTED"): "preproc",
    ("erlang", "RECORD"): "type", ("erlang", "RECORD QUOTED"): "type", ("erlang", "ATOM"): "constant",
    ("erlang", "ATOM QUOTED"): "constant", ("erlang", "NODE NAME"): "namespace",
    ("erlang", "NODE NAME QUOTED"): "namespace", ("erlang", "MODULE ATTRIBUTES"): "decorator",
    ("verilog", "KEYWORD"): "type", ("verilog", "USER"): "u1",
    ("vhdl", "STD OPERATOR"): "keyword", ("vhdl", "ATTRIBUTE"): "decorator",
    ("go", "PREDECLARED IDENTIFIERS"): "function.builtin",
    ("perl", "SCALAR"): "variable", ("perl", "ARRAY"): "variable", ("perl", "HASH"): "variable",
    ("perl", "SYMBOL TABLE"): "variable", ("perl", "PROTOTYPE"): "type", ("perl", "TRANSLATION"): "regexp",
    ("perl", "HEREDOC DELIMITER"): "keyword", ("perl", "FORMAT IDENTIFIER"): "function",
    ("perl", "FORMAT BODY"): "string", ("perl", "DATA SECTION"): "comment", ("perl", "POD VERBATIM"): "code",
    ("objc", "DIRECTIVE"): "keyword", ("objc", "QUALIFIER"): "storage",
    ("asm", "CPU INSTRUCTION"): "keyword", ("asm", "MATH INSTRUCTION"): "function",
    ("asm", "REGISTER"): "variable.builtin", ("asm", "DIRECTIVE"): "preproc", ("asm", "DIRECTIVE OPERAND"): "parameter",
    ("asm", "EXT INSTRUCTION"): "function.builtin",
    ("fortran", "FUNCTION1"): "function.builtin", ("fortran", "FUNCTION2"): "function",
    ("fortran", "OPERATOR2"): "keyword", ("fortran", "LABEL"): "decorator", ("fortran", "CONTINUATION"): "operator",
    ("coffeescript", "TYPE WORD"): "keyword", ("coffeescript", "PREDEFINED CONSTANT"): "constant",
    ("coffeescript", "VERBOSE REGEX"): "regexp",
    ("nsis", "FUNCTION"): "function.builtin", ("nsis", "VARIABLE"): "variable.builtin", ("nsis", "LABEL"): "decorator",
    ("nsis", "USER DEFINED"): "u1", ("nsis", "SECTION"): "section", ("nsis", "SUBSECTION"): "section",
    ("nsis", "SECTION GROUP"): "section", ("nsis", "IF DEFINE"): "preproc", ("nsis", "MACRO"): "preproc",
    ("nsis", "STRING VAR"): "string.escape", ("nsis", "PAGE EX"): "keyword", ("nsis", "FUNCTION DEFINITIONS"): "keyword",
    ("nsis", "STRING LEFT QUOTE"): "string", ("nsis", "STRING RIGHT QUOTE"): "string",
    ("ada", "DELIMITER"): "punctuation", ("ada", "ILLEGAL"): "invalid",
    ("asn1", "NUMERIC OID DEFINITION"): "number", ("asn1", "DESCRIPTORS"): "decorator", ("asn1", "TYPES"): "type",
    ("asp", "ASP SYMBOL"): "preproc", ("asp", "SCRIPT TYPE"): "preproc",
    ("avs", "FILTER"): "function.builtin", ("avs", "PLUGIN"): "function", ("avs", "CLIP PROPERTIES"): "property",
    ("avs", "USER DEFINED"): "u1",
    ("baanc", "FUNCTIONS"): "function.builtin", ("baanc", "FUNCTIONS ABRIDGED"): "function.builtin",
    ("baanc", "SUB SECTIONS"): "keyword", ("baanc", "MAIN SECTIONS"): "section",
    ("baanc", "PREDEFINED VARIABLE"): "variable.builtin", ("baanc", "PREDEFINED ATTRIBUTES"): "property",
    ("baanc", "ENUM DOMAINS"): "constant", ("baanc", "USER DEFINED"): "u1", ("baanc", "TABLE DEFINITIONS"): "type",
    ("baanc", "TABLE SQL"): "keyword", ("baanc", "DLL FUNCTIONS"): "function", ("baanc", "DOMAIN DEFINITIONS"): "type",
    ("baanc", "FUNCTION DEFINITIONS"): "function", ("baanc", "OBJECT DEFINITIONS"): "type",
    ("baanc", "PREPROC DEFINITIONS"): "preproc",
    **{(b, k): r for b in ("blitzbasic", "freebasic", "purebasic")
       for k, r in (("KEYWORD2", "function.builtin"), ("KEYWORD3", "type"), ("KEYWORD4", "constant"),
                    ("CONSTANT", "constant"))},
    ("caml", "BUILIN FUNC & TYPE"): "function.builtin", ("caml", "TAGNAME"): "constant", ("caml", "LINENUM"): "preproc",
    ("cobol", "DECLARATION"): "storage",
    ("csound", "INSTR"): "keyword", ("csound", "HEADER STATEMENT"): "keyword", ("csound", "USER KEYWORDS"): "u1",
    ("csound", "A-RATE VARIABLE"): "variable", ("csound", "K-RATE VARIABLE"): "variable",
    ("csound", "I-RATE VARIABLE"): "variable", ("csound", "GLOBAL VARIABLE"): "variable.builtin",
    ("csound", "END OF LINE WHERE STRING IS NOT CLOSED"): "invalid",
    ("d", "KEYWORD2"): "type", ("d", "KEYWORD3"): "function.builtin", ("d", "KEYWORD4"): "u1",
    ("d", "KEYWORD5"): "u2", ("d", "KEYWORD6"): "u3",
    ("escript", "BRACES"): "punctuation", ("escript", "KEYWORDS2"): "function.builtin", ("escript", "KEYWORDS3"): "type",
    ("forth", "KEYWORDS"): "function.builtin", ("forth", "DEFWORDS"): "storage", ("forth", "PREWORD1"): "preproc",
    ("forth", "PREWORD2"): "preproc", ("forth", "LOCALE"): "constant",
    ("fortran77", "FUNCTION1"): "function.builtin", ("fortran77", "FUNCTION2"): "function",
    ("fortran77", "OPERATOR2"): "keyword", ("fortran77", "LABEL"): "decorator", ("fortran77", "CONTINUATION"): "operator",
    ("gdscript", "FUNC NAME"): "function", ("gdscript", "WORD2"): "type.builtin", ("gdscript", "ANNOTATION"): "decorator",
    ("gdscript", "NODEPATH"): "constant", ("gdscript", "STRING EOL"): "invalid",
    ("gui4cli", "EVENT"): "function", ("gui4cli", "CONTROL"): "keyword", ("gui4cli", "COMMAND"): "function.builtin",
    ("hollywood", "CORE API"): "function.builtin", ("hollywood", "PLUGIN API"): "function",
    ("hollywood", "PLUGIN METHOD"): "function", ("hollywood", "CONSTANT"): "constant",
    ("mssql", "DATA TYPE"): "type.builtin", ("mssql", "SYSTEM TABLE"): "type", ("mssql", "GLOBAL"): "variable.builtin",
    ("mssql", "SYSTEM STORED PROC"): "function.builtin", ("mssql", "COL NAME"): "property",
    ("mssql", "COL NAME IN []'s"): "property",
    ("mmixal", "OPCODE"): "keyword", ("mmixal", "UNKNOWN OPCODE"): "invalid", ("mmixal", "REFERENCE (TO A LABEL)"): "decorator",
    ("mmixal", "CHAR"): "string", ("mmixal", "REGISTER"): "variable.builtin", ("mmixal", "SYMBOL"): "constant",
    ("nim", "CLASS NAME DEFINITION"): "type", ("nim", "FUNCTION OR METHOD NAME DEFINITION"): "function",
    ("nim", "HIGHLIGHTED IDENTIFIERS"): "variable.builtin", ("nim", "DECORATORS"): "decorator",
    ("nim", "END OF LINE WHERE STRING IS NOT CLOSED"): "invalid",
    ("oscript", "#IFDEF DOC AND #ENDIF"): "comment", ("oscript", "CONSTANT LITERAL"): "constant",
    ("oscript", "SERVER-GLOBAL VARIABLE (PREFIXED BY $)"): "variable.builtin",
    ("oscript", "OPERATOR; EITHER SYMBOLIC OR LITERAL"): "operator",
    ("oscript", "LABEL TO JUMP TO WITH THE GOTO STATEMENT"): "decorator",
    ("oscript", "OBJECT PROPERTY"): "property", ("oscript", "OBJECT METHOD"): "function",
    ("postscript", "DSC VALUE"): "constant", ("postscript", "Name"): "variable", ("postscript", "LITERAL"): "constant",
    ("postscript", "IMMEVAL"): "preproc", ("postscript", "PAREN ARRAY"): "punctuation",
    ("postscript", "PAREN DICT"): "punctuation", ("postscript", "PAREN PROC"): "punctuation",
    ("postscript", "TEXT"): "string", ("postscript", "BAD STRING CHAR"): "invalid",
    ("raku", "ADVERB"): "decorator", ("raku", "MU"): "variable.builtin", ("raku", "POSITIONAL"): "variable",
    ("raku", "ASSOCIATIVE"): "variable", ("raku", "CALLABLE"): "function", ("raku", "GRAMMAR"): "type",
    ("raku", "CLASS"): "type", ("raku", "STRING VAR"): "string.escape", ("raku", "REGEX VAR"): "string.escape",
    ("rebol", "PREFACE"): "comment", ("rebol", "PAIR ( 800X600 )"): "number", ("rebol", "TUPLE ( 127.0.0.1 )"): "number",
    ("rebol", "BINARY ( 16#{1A803F59} )"): "number", ("rebol", "MONEY"): "number",
    ("rebol", "ISSUE { #123-CD-456 }"): "constant", ("rebol", "TAG { <TITLE HEIGHT=100> }"): "tag",
    ("rebol", "FILE { %/C/WINNT/SOME.DLL }"): "string", ("rebol", "EMAIL { JOE@MAIL.DOM }"): "link",
    ("rebol", "URL { FTP://THERE.DOM }"): "link", ("rebol", "DATE { 17-FEB-2004 1/3/99 }"): "number",
    ("rebol", "TIME { 12:30 11:22:59 01:59:59.123 }"): "number",
    ("rebol", "KEYWORD (TEST FUNCTIONS)"): "function.builtin", ("rebol", "KEYWORD (DATATYPES)"): "type",
    ("rebol", "KEYWORD 4"): "u1", ("rebol", "KEYWORD 5"): "u2", ("rebol", "KEYWORD 6"): "u3", ("rebol", "KEYWORD 7"): "u4",
    ("sas", "MACRO FUNCTION"): "function.builtin", ("sas", "STATEMENT"): "keyword",
    ("scheme", "FUNCTION WORD"): "keyword", ("scheme", "FUNCTION WORD2"): "function.builtin",
    ("scheme", "SYMBOL"): "constant", ("scheme", "SPECIAL"): "decorator",
    ("smalltalk", "SYMBOL"): "constant", ("smalltalk", "BINARY"): "operator", ("smalltalk", "BOOL"): "boolean",
    ("smalltalk", "SELF"): "variable.builtin", ("smalltalk", "SUPER"): "variable.builtin", ("smalltalk", "NIL"): "constant",
    ("smalltalk", "GLOBAL"): "type", ("smalltalk", "RETURN"): "keyword", ("smalltalk", "SPECIAL"): "punctuation",
    ("smalltalk", "KWS END"): "function", ("smalltalk", "ASSIGN"): "operator", ("smalltalk", "SPECIAL SELECTOR"): "keyword",
    ("spice", "KEYWORD2"): "function.builtin", ("spice", "KEYWORD3"): "type",
    ("spice", "OPERATORS (DELIMITERS)"): "operator", ("spice", "VALUE"): "number",
    ("txt2tags", "SPECIAL"): "punctuation", ("txt2tags", "STRONG"): "strong", ("txt2tags", "STRONG 2 (NOT USED)"): "strong",
    ("txt2tags", "EM1 (ITALIC)"): "emphasis", ("txt2tags", "EM2 (UNDERLINE)"): "emphasis",
    **{("txt2tags", f"H{i}"): "heading" for i in range(1, 7)},
    ("txt2tags", "PRECHAR (NOT USED)"): "punctuation", ("txt2tags", "ULIST"): "keyword", ("txt2tags", "OLIST"): "keyword",
    ("txt2tags", "BLOCKQUOTE"): "quote", ("txt2tags", "STRIKEOUT"): "comment", ("txt2tags", "HRULE"): "punctuation",
    ("txt2tags", "LINK"): "link", ("txt2tags", "CODE"): "code", ("txt2tags", "CODE2"): "code",
    ("txt2tags", "CODEBLOCK"): "code", ("txt2tags", "OPTION"): "decorator", ("txt2tags", "PREPROC"): "preproc",
    ("txt2tags", "POSTPROC"): "preproc",
    ("visualprolog", "MINOR"): "keyword", ("visualprolog", "COMMENT KEY"): "doc_keyword",
    ("visualprolog", "COMMENT KEY ERROR"): "error_badge", ("visualprolog", "ANONYMOUS"): "variable.builtin",
    ("visualprolog", "CHARACTER TOO MANY"): "invalid",
    ("escseq", "Sequence Identifier"): "punctuation", ("escseq", "Sequence Unknown"): "invalid",
}

# Intel HEX and S-Record: tell the record fields apart.
HEX_FIELDS = {
    "RECSTART": "keyword", "RECTYPE": "type", "BYTECOUNT": "function", "NOADDRESS": "comment",
    "DATAADDRESS": "number", "STARTADDRESS": "number", "EXTENDEDADDRESS": "number", "RECCOUNT": "number",
    "DATA_ODD": "default", "DATA_EVEN": "property", "DATA_EMPTY": "comment", "CHECKSUM": "string.escape",
}

# Generic rules on the style name, first match wins.
RULES = [
    (r"COMMENT DOC KEYWORD ERROR", "error_badge"),
    (r"COMMENT DOC KEYWORD|DOCUMENTATION (HELPER|MACRO)", "doc_keyword"),
    (r"COMMENT|^POD", "comment"),
    (r"ERROR|GARBAGE|_WRONG|_UNKNOWN", "invalid"),
    (r"^USER (KEYWORDS|ATTRIBUTES|TAGS|SCALAR) ?\d$", "user"),
    (r"^(DEFAULT|WHITE ?SPACE|IDENTIFIER|TEXT)$", "default"),
    (r"^SGML (DEFAULT|1ST PARAM|BLOCK DEFAULT)$", "preproc"),
    (r"^VAR IN (REGEX|STRING|BACKTICKS|HEREDOC)", "string.escape"),
    (r"ESCAPE|^ENTITY$|^SPECIAL CHAR$", "string.escape"),
    (r"REGEX", "regexp"),
    (r"STRING|CHARACTER|TRIPLE|VERBATIM|HEREDOC|^HERE |BACKTICKS|TEMPLATE LIT|CDATA", "string"),
    (r"NUMBER|^HEX|DATETIME", "number"),
    (r"^DECORATOR$", "decorator"),
    (r"^MACRO$", "preproc"),
    (r"PREPROCESSOR|^DIRECTIVE$", "preproc"),
    (r"^(OPERATORS?|SYMBOLS?)$", "operator"),
    (r"^TAG", "tag"),
    (r"ATTRIBUTE", "attribute"),
    (r"^(TYPE WORD|TYPE|CLASS NAME|STD TYPE)$", "type"),
    (r"^(DEF NAME|FUNCTION|FUNCTION NAME|STD FUNCTION)$", "function"),
    (r"BUILT-?IN", "function.builtin"),
    (r"^(MODULE NAME|STD PACKAGE)$", "namespace"),
    (r"^(VARIABLE|VAR)$", "variable"),
    (r"ENVIRONMENT VARIABLE", "variable.builtin"),
    (r"^PARAM(ETER)?$", "parameter"),
    (r"^LABEL$", "decorator"),
    (r"INSTRUCTION|KEYWORD|^WORD$|RESERVED", "keyword"),
]
RULES = [(re.compile(p), r) for p, r in RULES]


def classify(lexer, name, kw):
    if (lexer, name) in OVERRIDES:
        return OVERRIDES[(lexer, name)]
    if lexer == "errorlist":
        return ERRORLIST.get(name, "error_line")
    if lexer in ("ihex", "srec", "tehex") and name in HEX_FIELDS:
        return HEX_FIELDS[name]
    for pat, role in RULES:
        if pat.search(name):
            return role
    if kw == "instre1":
        return "keyword"
    if kw == "type1":
        return "type"
    return "default"


def fs(styles):
    """fontStyle bits: 1 bold, 2 italic, 4 underline."""
    return (1 if "bold" in styles else 0) | (2 if "italic" in styles else 0) | (4 if "underline" in styles else 0)


# The ANSI names two lexers use: ErrorList's "ANSI COLOR …" and the escape-sequence view's "RED on BLACK".
ANSI_INDEX = {"BLACK": 0, "RED": 1, "GREEN": 2, "YELLOW": 3, "BROWN": 3, "BLUE": 4, "MAGENTA": 5, "CYAN": 6,
              "GRAY": 7, "WHITE": 7, "DARK GRAY": 8, "BRIGHT RED": 9, "BRIGHT GREEN": 10, "BRIGHT BLUE": 12,
              "BRIGHT MAGENTA": 13, "BRIGHT CYAN": 14}


def ansi_style(f, lexer, name):
    """(fg, bg, fontStyle) for the ANSI-colored styles of the ErrorList and escape-sequence lexers, else None."""
    if lexer == "errorlist" and name.startswith("ANSI COLOR "):
        color = name.removeprefix("ANSI COLOR ")
        # ErrorList names the brights by their plain names: YELLOW is bright yellow, WHITE bright white
        i = {"YELLOW": 11, "WHITE": 15}.get(color, ANSI_INDEX[color])
        return f.ansi[i], f.base, 0
    m = re.fullmatch(r"(BOLD )?(\w+) on (\w+)", name)
    if lexer == "escseq" and m:
        bold, fg, bg = m.groups()
        fg_hex = f.text if fg == "DEFAULT" else f.ansi[ANSI_INDEX[fg] + (8 if bold else 0)]
        bg_hex = f.base if bg == "DEFAULT" else f.ansi[ANSI_INDEX[bg]]
        return fg_hex, bg_hex, 1 if bold else 0
    return None


# ErrorList (the output of Run and of plugins): error lines red, diff lines like a diff.
ERRORLIST = {"DIFF Changed": "changed", "DIFF Addition": "added", "DIFF Deletion": "deleted",
             "DIFF Message": "diff_position", "Escape Sequence": "punctuation", "Unknown Escape Sequence": "invalid",
             "GCC Included-From Error": "comment", "GCC Excerpt Error": "default", "DEFAULT STYLE": "default"}


def role_styles(f):
    """role → (fg, bg, fontStyle)."""
    c = f
    u = ui(f)
    ink = u["ink"]
    roles = {}
    for syntax_role in ("comment", "keyword", "storage", "operator", "punctuation", "function", "function.builtin",
                        "string", "string.escape", "regexp", "number", "constant", "boolean", "type",
                        "type.builtin", "variable", "variable.builtin", "parameter", "property", "namespace",
                        "tag", "attribute", "decorator", "heading", "link", "code", "emphasis", "strong",
                        "quote", "invalid"):
        color, st = f.syntax(syntax_role)
        roles[syntax_role] = (color, c.base, fs(st))
    roles.update({
        "default": (c.text, c.base, 0),
        "preproc": (c.clay, c.base, 0),
        "doc_keyword": (c.overlay2, c.base, 3),
        "error_badge": (ink, c.red_hi, 0),
        "key": (f.syntax("function")[0], c.base, 0),  # JSON/TOML/INI keys, like the TextMate port
        "section": (c.orange, c.base, 1),
        "added": (c.green, c.base, 0),
        "deleted": (c.red_hi, c.base, 0),
        "changed": (c.yellow, c.base, 0),
        "error_line": (u["error"], c.base, 0),
        "diff_header": (c.text_hi, c.base, 1),  # file headers bold; hunk positions in denim
        "diff_position": (c.denim, c.base, 0),
        "search_header": (c.orange, c.mantle, 1),
        "file_header": (c.yellow, c.base, 1),
        "line_number": (u["line_nr"], c.base, 0),
        "hit_word": (c.text_hi, u["search"], 1),
        "current_line": (None, u["line"], None),
    })
    user = [c.yellow, c.sage, c.clay, c.denim, c.red_hi, c.green, c.orange_hi, c.subtext0]
    for i, col in enumerate(user, 1):
        roles[f"u{i}"] = (col, c.base, 0)
    return roles


def global_styles(f):
    c = f
    u = ui(f)
    ink = u["ink"]

    def fill(col):
        return {"fgColor": col, "bgColor": col}

    tabs = [c.orange, c.green, c.yellow, c.denim, c.red_hi]
    styles = [
        ("Default Style", 32, {"fgColor": c.text, "bgColor": c.base, "fontName": "Consolas", "fontStyle": "0", "fontSize": "10"}),
        ("Indent guideline style", 37, {"fgColor": c.surface1, "bgColor": c.base, "fontName": "", "fontStyle": "0", "fontSize": ""}),
        ("Brace highlight style", 34, {"fgColor": u["bracket_fg"], "bgColor": u["bracket_bg"], "fontName": "", "fontStyle": "1", "fontSize": ""}),
        ("Bad brace colour", 35, {"fgColor": ink, "bgColor": c.red_hi, "fontName": "", "fontStyle": "0", "fontSize": ""}),
        ("Current line background colour", 0, {"bgColor": u["line"]}),
        ("Selected text colour", 0, {"bgColor": u["selection"], "fgColor": c.text_hi}),
        ("Multi-selected text color", 0, {"bgColor": u["selection"]}),
        ("Caret colour", 2069, {"fgColor": u["cursor"]}),
        ("Multi-edit carets color", 0, {"fgColor": c.overlay2}),
        ("Edge colour", 0, {"fgColor": c.surface0}),
        ("Line number margin", 33, {"fgColor": u["line_nr"], "bgColor": c.base, "fontName": "", "fontStyle": "0", "fontSize": ""}),
        ("Bookmark margin", 0, {"bgColor": c.base}),
        ("Change History margin", 0, {"bgColor": c.base}),
        ("Change History modified", 0, fill(c.yellow)),
        ("Change History revert modified", 0, fill(c.denim)),
        ("Change History revert origin", 0, fill(c.sage)),
        ("Change History saved", 0, fill(c.green)),
        ("Fold", 0, {"fgColor": c.overlay1, "bgColor": c.base}),
        ("Fold active", 0, {"fgColor": c.orange}),
        ("Fold margin", 0, {"fgColor": c.base, "bgColor": c.base}),
        ("White space symbol", 0, {"fgColor": c.surface2, "bgColor": c.base}),
        # Indicators below are drawn translucent over the text, so they take the plain accent.
        ("Smart Highlighting", 29, {"bgColor": c.overlay0}),
        ("Find Mark Style", 31, {"bgColor": c.orange}),
        ("Find status: Not found", 0, {"fgColor": c.red_hi}),
        ("Find status: Message", 0, {"fgColor": c.sage}),
        ("Find status: Search end reached", 0, {"fgColor": c.yellow}),
        ("Mark Style 1", 25, {"bgColor": c.denim}),
        ("Mark Style 2", 24, {"bgColor": c.red_hi}),
        ("Mark Style 3", 23, {"bgColor": c.yellow}),
        ("Mark Style 4", 22, {"bgColor": c.sage}),
        ("Mark Style 5", 21, {"bgColor": c.green}),
        ("Incremental highlight all", 28, {"bgColor": c.yellow}),
        ("Tags match highlighting", 27, {"bgColor": c.overlay0}),
        ("Tags attribute", 26, {"bgColor": c.denim}),
        ("Active tab focused indicator", 0, {"fgColor": c.orange}),
        ("Active tab unfocused indicator", 0, {"fgColor": c.overlay0}),
        ("Active tab text", 0, {"fgColor": c.text_hi}),
        ("Inactive tabs", 0, {"fgColor": c.overlay1, "bgColor": c.crust}),
        *((f"Tab color {i}", 0, {"bgColor": col}) for i, col in enumerate(tabs, 1)),
        *((f"Tab color dark mode {i}", 0, {"bgColor": col}) for i, col in enumerate(tabs, 1)),
        ("URL hovered", 0, {"fgColor": c.denim_hi, "bgColor": c.base, "fontStyle": "0"}),
        ("Document map", 0, {"fgColor": c.overlay0, "bgColor": c.surface1}),
        ("EOL custom color", 0, {"fgColor": c.surface2}),
        ("Non-printing characters custom color", 0, {"fgColor": c.overlay0}),
        ("Global override", 0, {"fgColor": c.text, "bgColor": c.base, "fontName": "", "fontStyle": "0", "fontSize": ""}),
    ]
    return styles


def attrs(d):
    return " ".join(f"{k}={quoteattr(h(v) if k.endswith('Color') else v)}" for k, v in d.items())


def theme(f):
    roles = role_styles(f)
    lines = ['<?xml version="1.0" encoding="UTF-8" ?>', f"<!-- {HEADER} -->", "<NotepadPlus>", "    <LexerStyles>"]
    for lexer, desc, styles in lexers():
        lines.append(f'        <LexerType name="{lexer}" desc={quoteattr(desc)} ext="">')
        for sid, name, kw in styles:
            role = classify(lexer, name, kw)
            if role == "user":
                role = f"u{int(name[-1])}"
            fg, bg, style = ansi_style(f, lexer, name) or roles[role]
            d = {"name": name, "styleID": sid}
            if fg:
                d["fgColor"] = fg
            d["bgColor"] = bg
            if style is not None:
                d.update({"fontName": "", "fontStyle": str(style), "fontSize": ""})
            if kw:
                d["keywordClass"] = kw
            lines.append(f"            <WordsStyle {attrs(d)} />")
        lines.append("        </LexerType>")
    lines += ["    </LexerStyles>", "    <GlobalStyles>"]
    for name, sid, d in global_styles(f):
        lines.append(f"        <WidgetStyle {attrs({'name': name, 'styleID': str(sid), **d})} />")
    lines += ["    </GlobalStyles>", "</NotepadPlus>"]
    return "\n".join(lines) + "\n"


META["notes"] = (
    f"Syntax colors for all {len(lexers())} lexers Notepad++ ships, plus the editor chrome: margins, folding, "
    "tabs, change history, and smart and find highlights. Pair the dark flavors with Settings › Preferences › "
    "Dark Mode so the menus match."
)


def build(flavors):
    how = "portable install: the themes folder next to notepad++.exe; restart Notepad++ afterwards"
    return [
        Out(f"{f.name}.xml", theme(f), flavor=f.id, dest=f"%AppData%\\Notepad++\\themes\\{f.name}.xml",
            how=how, lang="xml")
        for f in flavors
    ]
