"""VS Code (and Cursor, Windsurf, VSCodium via Open VSX): a workbench theme per flavor."""

import json

import palette as p
from ports._lib import REPO, VERSION, Out, resolve, scope_rules, tints

a = p.alpha

META = {
    "id": "vscode",
    "name": "VS Code",
    "category": "Editors",
    "homepage": "https://code.visualstudio.com",
    "enable": {
        "where": "the Marketplace or Open VSX (Cursor, Windsurf, VSCodium), then Preferences: Color Theme",
        "code": "code --install-extension oddurs.subway-seat\n# settings.json\n\"workbench.colorTheme\": \"{name}\"",
        "lang": "json",
    },
    "notes": "All three flavors in one extension, with a fully layered workbench, TextMate and semantic "
    "token colors. Works in Cursor, Windsurf and VSCodium too.",
}


# (key, dark expression, light expression or None for the same)
LAYERS = [
 # ── grounds
 ("editor.background", "base", None),
 ("editorGutter.background", "base", None),
 ("breadcrumb.background", "base", None),
 ("editorGroupHeader.tabsBackground", "mantle", None),
 ("editorGroupHeader.noTabsBackground", "base", None),
 ("tab.activeBackground", "base", None),
 ("tab.unfocusedActiveBackground", "mix(base,mantle,0.5)", None),
 ("tab.inactiveBackground", "mantle", None),
 ("tab.hoverBackground", "text@L1", None),
 ("tab.unfocusedHoverBackground", "text@3", None),
 ("sideBar.background", "mantle", None),
 ("sideBarSectionHeader.background", "mantle", None),
 ("sideBarStickyScroll.background", "mantle", None),
 ("activityBar.background", "mantle", None),
 ("titleBar.activeBackground", "mantle", None),
 ("titleBar.inactiveBackground", "crust", None),
 ("statusBar.background", "mantle", None),
 ("statusBar.noFolderBackground", "mantle", None),
 ("panel.background", "mantle", None),
 ("panelStickyScroll.background", "mantle", None),
 ("editorStickyScroll.background", "base", None),
 ("editorStickyScrollHover.background", "text@L1", None),
 ("diffEditor.unchangedRegionBackground", "mantle", None),
 # ── structural seams
 ("sideBar.border", "crust", "text@EDGE"),
 ("activityBar.border", "mantle", None),
 ("titleBar.border", "crust", "text@EDGE"),
 ("statusBar.border", "crust", "text@EDGE"),
 ("panel.border", "crust", "text@EDGE"),
 ("panelSection.border", "crust", "text@EDGE"),
 ("editorGroup.border", "crust", "text@EDGE"),
 ("editorGroupHeader.tabsBorder", "crust", "text@EDGE"),
 ("tab.border", "mantle", None),
 ("tab.activeBorder", "base", None),
 ("tab.activeBorderTop", "orange", None),
 ("tab.unfocusedActiveBorder", "base", None),
 ("tab.unfocusedActiveBorderTop", "orange@35", None),
 ("tab.lastPinnedBorder", "text@L3", None),
 ("sideBarSectionHeader.border", "text@6", "text@8"),
 ("sideBarStickyScroll.shadow", "shadow@45", "shadow@10"),
 ("editorStickyScroll.shadow", "shadow@45", "shadow@10"),
 ("panelStickyScroll.shadow", "shadow@45", "shadow@10"),
 ("scrollbar.shadow", "shadow@45", "shadow@10"),
 ("focusBorder", "orange@50", "orange@60"),
 ("sash.hoverBorder", "orange@70", None),
 # ── widgets / popovers
 ("widget.shadow", "shadow@60", "shadow@14"),
 ("widget.border", "text@EDGE", None),
 ("editorWidget.background", "paper", None),
 ("editorWidget.border", "text@EDGE", None),
 ("editorSuggestWidget.background", "paper", None),
 ("editorSuggestWidget.border", "text@EDGE", None),
 ("editorSuggestWidget.selectedBackground", "text@L3", None),
 ("editorHoverWidget.background", "paper", None),
 ("editorHoverWidget.border", "text@EDGE", None),
 ("editorHoverWidget.statusBarBackground", "text@L1", None),
 ("quickInput.background", "paper", None),
 ("quickInputTitle.background", "text@L1", None),
 ("quickInputList.focusBackground", "text@L3", None),
 ("menu.background", "paper", None),
 ("menu.border", "text@EDGE", None),
 ("menu.selectionBackground", "text@L3", None),
 ("menu.separatorBackground", "text@L2", None),
 ("notifications.background", "paper", None),
 ("notifications.border", "text@EDGE", None),
 ("notificationToast.border", "text@EDGE", None),
 ("notificationCenter.border", "text@EDGE", None),
 ("notificationCenterHeader.background", "text@L1", None),
 ("debugToolBar.background", "paper", None),
 ("debugToolBar.border", "text@EDGE", None),
 ("breadcrumbPicker.background", "paper", None),
 ("peekView.border", "orange@50", None),
 ("peekViewTitle.background", "paper", None),
 ("peekViewEditor.background", "mantle", None),
 ("peekViewEditorGutter.background", "mantle", None),
 ("peekViewResult.background", "mantle", None),
 ("peekViewResult.selectionBackground", "text@L3", None),
 ("peekViewEditor.matchHighlightBackground", "yellow@22", "yellow@26"),
 ("peekViewResult.matchHighlightBackground", "yellow@22", "yellow@26"),
 # ── controls
 ("input.background", "base", "paper"),
 ("input.border", "text@10", "text@EDGE"),
 ("inputOption.activeBackground", "orange@20", "orange@16"),
 ("inputOption.activeBorder", "orange@60", None),
 ("dropdown.background", "base", "paper"),
 ("dropdown.listBackground", "paper", None),
 ("dropdown.border", "text@10", "text@EDGE"),
 ("checkbox.background", "base", "paper"),
 ("checkbox.border", "text@L4", None),
 ("button.background", "orange", "mix(text,orange,0.15)"),
 ("button.foreground", "crust", "paper"),
 ("button.hoverBackground", "orange_hi", "orange"),
 ("button.secondaryBackground", "text@L3", None),
 ("button.secondaryHoverBackground", "text@L4", None),
 ("button.separator", "crust@40", "base@40"),
 ("badge.background", "text@L3", "text@L3"),
 ("activityBarBadge.background", "orange", None),
 ("keybindingLabel.background", "text@6", None),
 ("keybindingLabel.border", "text@L3", None),
 ("keybindingLabel.bottomBorder", "text@L5", None),
 ("toolbar.hoverBackground", "text@L2", None),
 ("toolbar.activeBackground", "text@L3", None),
 ("actionBar.toggledBackground", "orange@18", "orange@14"),
 ("commandCenter.background", "text@L1", "paper"),
 ("commandCenter.border", "text@10", "text@EDGE"),
 ("commandCenter.activeBackground", "text@L2", None),
 ("commandCenter.activeBorder", "orange@50", None),
 ("selection.background", "text@20", "text@16"),
 # ── lists
 ("list.hoverBackground", "text@L1", None),
 ("list.inactiveSelectionBackground", "text@L2", None),
 ("list.activeSelectionBackground", "text@L3", None),
 ("list.focusBackground", "text@L3", None),
 ("list.inactiveFocusBackground", "text@L2", None),
 ("list.focusOutline", "orange@35", "orange@45"),
 ("list.inactiveFocusOutline", "transparent", None),
 ("list.focusAndSelectionOutline", "transparent", None),
 ("list.dropBackground", "orange@15", "orange@12"),
 ("list.filterMatchBackground", "yellow@18", "yellow@22"),
 ("editorGroup.dropBackground", "orange@10", "orange@8"),
 ("tree.indentGuidesStroke", "text@L5", None),
 ("tree.inactiveIndentGuidesStroke", "text@L2", None),
 ("statusBarItem.hoverBackground", "text@L2", None),
 ("statusBarItem.activeBackground", "text@L3", None),
 ("statusBarItem.prominentBackground", "text@L3", None),
 ("statusBarItem.remoteBackground", "orange", "mix(text,orange,0.15)"),
 ("statusBarItem.remoteForeground", "crust", "paper"),
 ("statusBarItem.errorBackground", "transparent", None),
 ("statusBarItem.warningBackground", "transparent", None),
 ("statusBar.debuggingBackground", "mix(red,mantle,0.35)", "mix(red,mantle,0.22)"),
 ("statusBar.debuggingBorder", "red@60", None),
 ("activityBar.activeBorder", "orange", None),
 ("panelTitle.activeBorder", "orange", None),
 # ── editor interior
 ("editor.lineHighlightBackground", "text@L1", None),
 ("editor.lineHighlightBorder", "transparent", None),
 ("editor.selectionBackground", "text@L4", None),
 ("editor.inactiveSelectionBackground", "text@9", "text@7"),
 ("editor.selectionHighlightBackground", "text@L2", None),
 ("editor.selectionHighlightBorder", "transparent", None),
 ("editor.wordHighlightBackground", "text@L2", None),
 ("editor.wordHighlightStrongBackground", "denim@18", "denim@14"),
 ("editor.wordHighlightTextBackground", "text@L2", None),
 ("editor.findMatchBackground", "orange@30", "orange@26"),
 ("editor.findMatchBorder", "orange@80", None),
 ("editor.findMatchHighlightBackground", "yellow@15", "yellow@22"),
 ("editor.findMatchHighlightBorder", "transparent", None),
 ("editor.findRangeHighlightBackground", "text@L1", None),
 ("editor.rangeHighlightBackground", "yellow@8", "yellow@12"),
 ("editor.hoverHighlightBackground", "text@L2", None),
 ("editor.linkedEditingBackground", "denim@14", "denim@12"),
 ("editor.foldBackground", "text@5", None),
 ("editor.stackFrameHighlightBackground", "yellow@12", "yellow@16"),
 ("editor.focusedStackFrameHighlightBackground", "green@12", "green@14"),
 ("editorBracketMatch.background", "text@10", "text@8"),
 ("editorBracketMatch.border", "text@30", "text@28"),
 ("editorIndentGuide.background1", "text@7", "text@8"),
 ("editorIndentGuide.activeBackground1", "text@20", "text@22"),
 ("editorWhitespace.foreground", "text@14", "text@16"),
 ("editorRuler.foreground", "text@L2", None),
 ("editorInlayHint.background", "text@6", "text@5"),
 ("editorOverviewRuler.border", "transparent", None),
 ("editorLineNumber.foreground", "overlay0", None),
 ("editorLineNumber.activeForeground", "subtext1", None),
 ("editorLineNumber.dimmedForeground", "surface2", "surface1"),
 ("editorCodeLens.foreground", "overlay0", None),
 ("editorGhostText.foreground", "overlay0", None),
 ("editorInlayHint.foreground", "overlay1", None),
 # ── brackets (hue @ alpha so they sit under identifiers)
 ("editorBracketHighlight.foreground1", "yellow@85", None),
 ("editorBracketHighlight.foreground2", "orange@85", None),
 ("editorBracketHighlight.foreground3", "sage@85", None),
 ("editorBracketHighlight.foreground4", "clay@85", None),
 ("editorBracketHighlight.foreground5", "denim@85", None),
 ("editorBracketHighlight.foreground6", "overlay2", None),
 ("editorBracketHighlight.unexpectedBracket.foreground", "red_hi", "red"),
 ("editorBracketPairGuide.activeBackground1", "yellow@60", None),
 ("editorBracketPairGuide.background1", "yellow@20", None),
 # ── scrollbar / minimap
 ("scrollbarSlider.background", "text@9", "text@12"),
 ("scrollbarSlider.hoverBackground", "text@L4", "text@18"),
 ("scrollbarSlider.activeBackground", "orange@40", None),
 ("minimapSlider.background", "text@7", "text@10"),
 ("minimapSlider.hoverBackground", "text@12", "text@15"),
 ("minimapSlider.activeBackground", "orange@30", None),
 ("minimap.selectionHighlight", "text@30", "text@25"),
 ("minimap.findMatchHighlight", "yellow@70", None),
 ("minimapGutter.addedBackground", "green@70", None),
 ("minimapGutter.modifiedBackground", "yellow@70", None),
 ("minimapGutter.deletedBackground", "red_hi@70", "red@70"),
 # ── diff / merge / scm gutter
 ("diffEditor.insertedLineBackground", "green@10", "green@12"),
 ("diffEditor.insertedTextBackground", "green@22", "green@24"),
 ("diffEditor.removedLineBackground", "red@12", "red@9"),
 ("diffEditor.removedTextBackground", "red@26", "red@20"),
 ("diffEditorGutter.insertedLineBackground", "green@18", "green@20"),
 ("diffEditorGutter.removedLineBackground", "red@20", "red@16"),
 ("diffEditor.diagonalFill", "text@L2", None),
 ("diffEditor.border", "crust", "text@EDGE"),
 ("merge.currentHeaderBackground", "green@35", "green@30"),
 ("merge.currentContentBackground", "green@12", "green@12"),
 ("merge.incomingHeaderBackground", "denim@35", "denim@30"),
 ("merge.incomingContentBackground", "denim@12", "denim@12"),
 ("merge.commonHeaderBackground", "text@20", "text@16"),
 ("merge.commonContentBackground", "text@6", "text@5"),
 ("editorGutter.addedBackground", "green@80", None),
 ("editorGutter.modifiedBackground", "yellow@80", None),
 ("editorGutter.deletedBackground", "red_hi@80", "red@80"),
 # ── terminal
 ("terminal.selectionBackground", "text@20", "text@16"),
 ("terminal.inactiveSelectionBackground", "text@10", "text@8"),
 ("terminal.findMatchBackground", "orange@30", "orange@26"),
 ("terminal.findMatchHighlightBackground", "yellow@15", "yellow@22"),
 ("terminal.border", "crust", "text@EDGE"),
 ("terminalStickyScroll.background", "mantle", None),
 ("terminalStickyScrollHover.background", "text@L1", None),
]

# Foregrounds that go with the layered grounds.
LAYERS += [
    ("foreground", "subtext1", None),
    ("editor.foreground", "text", None),
    ("sideBar.foreground", "subtext0", None),
    ("sideBarTitle.foreground", "subtext1", None),
    ("sideBarSectionHeader.foreground", "subtext1", None),
    ("tab.activeForeground", "text_hi", None),
    ("tab.inactiveForeground", "overlay1", None),
    ("tab.unfocusedActiveForeground", "subtext0", None),
    ("tab.unfocusedInactiveForeground", "overlay0", None),
    ("list.activeSelectionForeground", "text_hi", None),
    ("list.inactiveSelectionForeground", "text", None),
    ("list.hoverForeground", "text", None),
    ("list.highlightForeground", "yellow", None),
    ("list.focusHighlightForeground", "yellow_hi", "yellow"),
    ("titleBar.activeForeground", "subtext0", None),
    ("titleBar.inactiveForeground", "overlay0", None),
    ("statusBar.foreground", "subtext0", None),
    ("statusBar.noFolderForeground", "subtext0", None),
    ("statusBar.debuggingForeground", "text_hi", None),
    ("activityBar.foreground", "text", None),
    ("activityBar.inactiveForeground", "overlay1", None),
    ("activityBarBadge.foreground", "crust", "paper"),
    ("badge.foreground", "text_hi", None),
    ("button.secondaryForeground", "text", None),
    ("statusBarItem.errorForeground", "red_hi", "red"),
    ("statusBarItem.warningForeground", "yellow", None),
    ("statusBarItem.prominentForeground", "text_hi", None),
    ("panelTitle.activeForeground", "text_hi", None),
    ("panelTitle.inactiveForeground", "overlay1", None),
    ("quickInput.foreground", "text", None),
    ("quickInputList.focusForeground", "text_hi", None),
    ("menu.foreground", "text", None),
    ("menu.selectionForeground", "text_hi", None),
    ("editorSuggestWidget.foreground", "subtext1", None),
    ("editorSuggestWidget.selectedForeground", "text_hi", None),
    ("editorSuggestWidget.highlightForeground", "yellow", None),
    ("editorSuggestWidget.focusHighlightForeground", "yellow_hi", "yellow"),
    ("notifications.foreground", "text", None),
    ("input.foreground", "text", None),
    ("input.placeholderForeground", "overlay0", None),
    ("inputOption.activeForeground", "text_hi", None),
    ("dropdown.foreground", "text", None),
    ("keybindingLabel.foreground", "text", None),
    ("breadcrumb.foreground", "overlay1", None),
    ("breadcrumb.focusForeground", "text", None),
    ("breadcrumb.activeSelectionForeground", "yellow", None),
    ("editorCursor.foreground", "yellow", "orange"),
    ("editorCursor.background", "base", None),
    ("terminalCursor.foreground", "yellow", "orange"),
    ("icon.foreground", "subtext0", None),
]

# AI panels and the VS Code forks. Cursor, Windsurf and Kiro derive their agent
# UIs from standard keys, plus a handful of their own.
LAYERS += [
    ("chat.requestBackground", "text@L1", None),
    ("chat.requestBorder", "text@L2", None),
    ("chat.slashCommandBackground", "orange@18", "orange@14"),
    ("chat.slashCommandForeground", "orange", None),
    ("chat.avatarBackground", "text@L3", None),
    ("chat.avatarForeground", "text", None),
    ("chat.editedFileForeground", "yellow", None),
    ("chat.linesAddedForeground", "green", None),
    ("chat.linesRemovedForeground", "red_hi", "red"),
    ("inlineChat.background", "paper", None),
    ("inlineChat.border", "text@EDGE", None),
    ("inlineChat.shadow", "shadow@60", "shadow@14"),
    ("inlineChat.foreground", "text", None),
    ("inlineChatInput.background", "base", "paper"),
    ("inlineChatInput.border", "text@10", "text@EDGE"),
    ("inlineChatInput.focusBorder", "orange@50", "orange@60"),
    ("inlineChatInput.placeholderForeground", "overlay0", None),
    ("inlineChatDiff.inserted", "green@22", "green@24"),
    ("inlineChatDiff.removed", "red@26", "red@20"),
    ("editorWatermark.foreground", "overlay0", None),
    ("tab.worktreeBorder", "sage", None),
    ("diffEditor.insertedTextBackgroundCustom", "green@22", "green@24"),
    ("diffEditor.insertedTextBackgroundFallback", "green@22", "green@24"),
    ("diffEditor.removedTextBackgroundCustom", "red@26", "red@20"),
    ("diffEditor.removedTextBackgroundFallback", "red@26", "red@20"),
    ("diffEditor.windsurfRemovedTextBackground", "red@26", "red@20"),
    ("list.hoverBackground.subtle", "text@3", None),
    ("starkButton.background", "orange", "mix(text,orange,0.15)"),
    ("starkButton.foreground", "crust", "paper"),
    ("starkButton.hoverBackground", "orange_hi", "orange"),
    ("windsurf.black", "crust", None),
    ("windsurf.sea", "orange", None),
    ("windsurf.sea.shade", "mix(orange,base,0.7)", None),
    ("windsurf.sea.tint", "orange_hi", None),
    ("windsurf.sessionStatus.blue", "denim", None),
    ("windsurf.sessionStatus.green", "green", None),
    ("windsurf.sessionStatus.orange", "orange", None),
    ("windsurf.sessionStatus.purple", "clay", None),
    ("windsurf.sessionStatus.red", "red_hi", "red"),
    ("accent", "orange", None),
    ("background.gradientStart", "mantle", None),
    ("background.gradientEnd", "base", None),
    ("activityBar.activeGradientStart", "orange", None),
    ("activityBar.activeGradientEnd", "yellow", None),
    ("button.gradient", "orange", None),
    ("alertButton.background", "yellow", None),
    ("alertButton.foreground", "crust", "paper"),
    ("alertButton.hoverBackground", "yellow_hi", None),
    ("alertButton.hoverForeground", "crust", "paper"),
    ("alertButton.secondaryBackground", "text@L3", None),
    ("alertButton.secondaryForeground", "text", None),
    ("alertButton.secondaryHoverBackground", "text@L4", None),
    ("alertButton.secondaryHoverForeground", "text_hi", None),
    ("autonomyToggle.background", "text@L2", None),
    ("autonomyToggle.foreground", "subtext1", None),
    ("autonomyToggle.selectedBackground", "orange@20", "orange@16"),
    ("autonomyToggle.selectedIconForeground", "orange", None),
    ("autonomyToggle.selectedGradientStart", "orange", None),
    ("autonomyToggle.selectedGradientEnd", "yellow", None),
    ("inlineDiffToolbar.hotkeyBackground", "text@L3", None),
    ("inlineDiffToolbar.hotkeyForeground", "text", None),
    ("keybindingLabel.shadow", "shadow@45", "shadow@10"),
    ("panelTitle.activeBackground", "text@L1", None),
    ("quickInput.overlayBackground", "shadow@50", "shadow@20"),
    ("debugTokenExpression.name", "subtext1", None),
    ("debugTokenExpression.value", "text", None),
    ("debugTokenExpression.string", "green", None),
    ("debugTokenExpression.number", "red_hi", "red"),
    ("debugTokenExpression.boolean", "red_hi", "red"),
    ("debugTokenExpression.type", "sage", None),
    ("debugTokenExpression.error", "red_hi", "red"),
]


# Symbol icons (outline, breadcrumbs, suggest), following the syntax roles.
LAYERS += [
    (f"symbolIcon.{kind}Foreground", role, None)
    for kind, role in [
        ("array", "clay"), ("boolean", "red_hi"), ("class", "sage"), ("color", "clay"),
        ("constant", "red_hi"), ("constructor", "sage"), ("enumerator", "sage"),
        ("enumeratorMember", "red_hi"), ("event", "clay"), ("field", "subtext1"), ("file", "text"),
        ("folder", "yellow"), ("function", "yellow"), ("interface", "sage"), ("key", "orange"),
        ("keyword", "orange"), ("method", "yellow"), ("module", "subtext0"), ("namespace", "subtext0"),
        ("null", "red_hi"), ("number", "red_hi"), ("object", "sage"), ("operator", "overlay2"),
        ("package", "subtext0"), ("property", "subtext1"), ("reference", "denim"), ("snippet", "clay"),
        ("string", "green"), ("struct", "sage"), ("text", "text"), ("typeParameter", "sage"),
        ("unit", "red_hi"), ("variable", "text"),
    ]
]

def layered(f):
    return {key: resolve(light if (light and not f.dark) else dark, f) for key, dark, light in LAYERS}



def theme(f):
    c = f
    ansi_names = ["Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White"]
    colors = {
        # base
        "focusBorder": a(c.orange, 0.5),
        "foreground": c.subtext1,
        "disabledForeground": c.overlay0,
        "descriptionForeground": c.overlay1,
        "errorForeground": c.red_hi,
        "icon.foreground": c.subtext0,
        "selection.background": a(c.surface2, 0.9),
        "widget.shadow": "#0000004D",
        "sash.hoverBorder": c.orange,
        "textLink.foreground": c.denim,
        "textLink.activeForeground": c.denim_hi,
        "textPreformat.foreground": c.green,
        "textCodeBlock.background": c.crust,
        "textBlockQuote.background": c.mantle,
        "textBlockQuote.border": c.orange,
        "textSeparator.foreground": c.surface2,
        # title / activity / sidebar
        "titleBar.activeBackground": c.crust,
        "titleBar.activeForeground": c.subtext0,
        "titleBar.inactiveBackground": c.crust,
        "titleBar.inactiveForeground": c.overlay0,
        "titleBar.border": c.crust,
        "activityBar.background": c.crust,
        "activityBar.foreground": c.yellow,
        "activityBar.inactiveForeground": c.overlay0,
        "activityBar.activeBorder": c.yellow,
        "activityBar.activeBackground": c.mantle,
        "activityBar.border": c.crust,
        "activityBarBadge.background": c.orange,
        "activityBarBadge.foreground": c.crust,
        "activityBarTop.foreground": c.yellow,
        "activityBarTop.inactiveForeground": c.overlay0,
        "activityBarTop.activeBorder": c.yellow,
        "sideBar.background": c.mantle,
        "sideBar.foreground": c.subtext0,
        "sideBar.border": c.crust,
        "sideBarTitle.foreground": c.subtext1,
        "sideBarSectionHeader.background": c.mantle,
        "sideBarSectionHeader.foreground": c.subtext1,
        "sideBarSectionHeader.border": c.surface0,
        "sideBarActivityBarTop.border": c.crust,
        # lists & trees
        "list.activeSelectionBackground": c.surface1,
        "list.activeSelectionForeground": c.text_hi,
        "list.inactiveSelectionBackground": c.surface0,
        "list.inactiveSelectionForeground": c.text,
        "list.hoverBackground": a(c.surface0, 0.7),
        "list.hoverForeground": c.text,
        "list.focusOutline": a(c.orange, 0.6),
        "list.focusBackground": c.surface0,
        "list.highlightForeground": c.yellow,
        "list.focusHighlightForeground": c.yellow_hi,
        "list.errorForeground": c.red_hi,
        "list.warningForeground": c.yellow,
        "list.dropBackground": a(c.orange, 0.2),
        "listFilterWidget.background": c.mantle,
        "listFilterWidget.outline": c.orange,
        "tree.indentGuidesStroke": c.surface1,
        "tree.inactiveIndentGuidesStroke": c.surface0,
        # editor groups & tabs
        "editorGroup.border": c.crust,
        "editorGroup.dropBackground": a(c.orange, 0.15),
        "editorGroupHeader.tabsBackground": c.mantle,
        "editorGroupHeader.tabsBorder": c.crust,
        "editorGroupHeader.noTabsBackground": c.base,
        "tab.activeBackground": c.base,
        "tab.activeForeground": c.text_hi,
        "tab.activeBorderTop": c.orange,
        "tab.activeBorder": c.base,
        "tab.inactiveBackground": c.mantle,
        "tab.inactiveForeground": c.overlay1,
        "tab.unfocusedActiveBackground": c.base,
        "tab.unfocusedActiveForeground": c.subtext0,
        "tab.unfocusedActiveBorderTop": c.overlay0,
        "tab.unfocusedInactiveForeground": c.overlay0,
        "tab.hoverBackground": c.surface0,
        "tab.hoverForeground": c.text,
        "tab.border": c.crust,
        "tab.lastPinnedBorder": c.surface2,
        "tab.activeModifiedBorder": c.yellow,
        "tab.inactiveModifiedBorder": a(c.yellow, 0.5),
        "breadcrumb.foreground": c.overlay1,
        "breadcrumb.focusForeground": c.text,
        "breadcrumb.activeSelectionForeground": c.yellow,
        "breadcrumbPicker.background": c.mantle,
        # editor
        "editor.background": c.base,
        "editor.foreground": c.text,
        "editorLineNumber.foreground": c.overlay0,
        "editorLineNumber.activeForeground": c.yellow,
        "editorCursor.foreground": c.yellow,
        "editorCursor.background": c.base,
        "editor.lineHighlightBackground": a(c.surface0, 0.75),
        "editor.lineHighlightBorder": "#00000000",
        "editor.selectionBackground": c.surface2,
        "editor.inactiveSelectionBackground": a(c.surface2, 0.55),
        "editor.selectionHighlightBackground": a(c.surface2, 0.5),
        "editor.wordHighlightBackground": a(c.surface2, 0.45),
        "editor.wordHighlightStrongBackground": a(c.orange, 0.22),
        "editor.findMatchBackground": a(c.orange, 0.45),
        "editor.findMatchBorder": c.orange,
        "editor.findMatchHighlightBackground": a(c.yellow, 0.22),
        "editor.findRangeHighlightBackground": a(c.surface1, 0.5),
        "editor.rangeHighlightBackground": a(c.surface1, 0.45),
        "editor.hoverHighlightBackground": a(c.surface2, 0.45),
        "editor.foldBackground": a(c.surface0, 0.6),
        "editor.linkedEditingBackground": a(c.orange, 0.15),
        "editorLink.activeForeground": c.denim_hi,
        "editorWhitespace.foreground": c.surface1,
        "editorIndentGuide.background1": c.surface0,
        "editorIndentGuide.activeBackground1": c.surface2,
        "editorRuler.foreground": c.surface0,
        "editorCodeLens.foreground": c.overlay1,
        "editorBracketMatch.background": a(c.surface2, 0.6),
        "editorBracketMatch.border": c.overlay0,
        "editorBracketHighlight.foreground1": c.yellow,
        "editorBracketHighlight.foreground2": c.orange,
        "editorBracketHighlight.foreground3": c.sage,
        "editorBracketHighlight.foreground4": c.clay,
        "editorBracketHighlight.foreground5": c.green,
        "editorBracketHighlight.foreground6": c.subtext1,
        "editorBracketHighlight.unexpectedBracket.foreground": c.red_hi,
        "editorBracketPairGuide.activeBackground1": a(c.yellow, 0.5),
        "editorBracketPairGuide.activeBackground2": a(c.orange, 0.5),
        "editorBracketPairGuide.activeBackground3": a(c.sage, 0.5),
        "editorBracketPairGuide.activeBackground4": a(c.clay, 0.5),
        "editorBracketPairGuide.activeBackground5": a(c.green, 0.5),
        "editorBracketPairGuide.activeBackground6": a(c.subtext1, 0.5),
        "editorInlayHint.foreground": c.overlay1,
        "editorInlayHint.background": a(c.surface0, 0.6),
        "editorGhostText.foreground": c.overlay0,
        "editorUnnecessaryCode.opacity": "#000000A0",
        "editorStickyScroll.background": c.base,
        "editorStickyScroll.shadow": "#00000066",
        "editorStickyScrollHover.background": c.surface0,
        "editorLightBulb.foreground": c.yellow,
        "editorLightBulbAutoFix.foreground": c.green,
        "editorError.foreground": c.red_hi,
        "editorWarning.foreground": c.yellow,
        "editorInfo.foreground": c.denim,
        "editorHint.foreground": c.sage,
        "problemsErrorIcon.foreground": c.red_hi,
        "problemsWarningIcon.foreground": c.yellow,
        "problemsInfoIcon.foreground": c.denim,
        "editorGutter.background": c.base,
        "editorGutter.addedBackground": c.green,
        "editorGutter.modifiedBackground": c.yellow,
        "editorGutter.deletedBackground": c.red_hi,
        "editorGutter.foldingControlForeground": c.overlay1,
        "editorOverviewRuler.border": c.crust,
        "editorOverviewRuler.addedForeground": a(c.green, 0.7),
        "editorOverviewRuler.modifiedForeground": a(c.yellow, 0.7),
        "editorOverviewRuler.deletedForeground": a(c.red_hi, 0.7),
        "editorOverviewRuler.errorForeground": c.red_hi,
        "editorOverviewRuler.warningForeground": c.yellow,
        "editorOverviewRuler.infoForeground": c.denim,
        "editorOverviewRuler.findMatchForeground": c.orange,
        "editorOverviewRuler.selectionHighlightForeground": c.surface2,
        "minimap.findMatchHighlight": c.orange,
        "minimap.selectionHighlight": c.surface2,
        "minimap.errorHighlight": c.red_hi,
        "minimap.warningHighlight": c.yellow,
        "minimapGutter.addedBackground": c.green,
        "minimapGutter.modifiedBackground": c.yellow,
        "minimapGutter.deletedBackground": c.red_hi,
        "scrollbar.shadow": "#00000066",
        "scrollbarSlider.background": a(c.surface2, 0.5),
        "scrollbarSlider.hoverBackground": a(c.surface2, 0.8),
        "scrollbarSlider.activeBackground": c.overlay0,
        # widgets
        "editorWidget.background": c.mantle,
        "editorWidget.foreground": c.text,
        "editorWidget.border": c.surface1,
        "editorWidget.resizeBorder": c.orange,
        "editorSuggestWidget.background": c.mantle,
        "editorSuggestWidget.border": c.surface1,
        "editorSuggestWidget.foreground": c.subtext1,
        "editorSuggestWidget.selectedBackground": c.surface1,
        "editorSuggestWidget.selectedForeground": c.text_hi,
        "editorSuggestWidget.highlightForeground": c.yellow,
        "editorSuggestWidget.focusHighlightForeground": c.yellow_hi,
        "editorHoverWidget.background": c.mantle,
        "editorHoverWidget.border": c.surface1,
        "editorHoverWidget.highlightForeground": c.yellow,
        "editorHoverWidget.statusBarBackground": c.crust,
        "debugExceptionWidget.background": c.mantle,
        "debugExceptionWidget.border": c.red,
        "peekView.border": c.orange,
        "peekViewTitle.background": c.crust,
        "peekViewTitleLabel.foreground": c.text_hi,
        "peekViewTitleDescription.foreground": c.overlay1,
        "peekViewEditor.background": c.mantle,
        "peekViewEditor.matchHighlightBackground": a(c.orange, 0.35),
        "peekViewResult.background": c.crust,
        "peekViewResult.selectionBackground": c.surface1,
        "peekViewResult.matchHighlightBackground": a(c.orange, 0.35),
        "peekViewResult.fileForeground": c.text,
        "peekViewResult.lineForeground": c.subtext0,
        # diff
        "diffEditor.insertedTextBackground": a(c.green, 0.24),
        "diffEditor.removedTextBackground": a(c.red, 0.28),
        "diffEditor.insertedLineBackground": a(c.green, 0.1),
        "diffEditor.removedLineBackground": a(c.red, 0.12),
        "diffEditor.diagonalFill": c.surface0,
        "diffEditorGutter.insertedLineBackground": a(c.green, 0.2),
        "diffEditorGutter.removedLineBackground": a(c.red, 0.22),
        "merge.currentHeaderBackground": a(c.green, 0.4),
        "merge.currentContentBackground": a(c.green, 0.14),
        "merge.incomingHeaderBackground": a(c.denim, 0.4),
        "merge.incomingContentBackground": a(c.denim, 0.14),
        "merge.commonHeaderBackground": a(c.overlay0, 0.5),
        "merge.commonContentBackground": a(c.overlay0, 0.2),
        # inputs & controls
        "input.background": c.crust,
        "input.foreground": c.text,
        "input.border": c.surface1,
        "input.placeholderForeground": c.overlay0,
        "inputOption.activeBorder": c.orange,
        "inputOption.activeBackground": a(c.orange, 0.2),
        "inputOption.activeForeground": c.text_hi,
        "inputValidation.errorBackground": c.mantle,
        "inputValidation.errorBorder": c.red_hi,
        "inputValidation.warningBackground": c.mantle,
        "inputValidation.warningBorder": c.yellow,
        "inputValidation.infoBackground": c.mantle,
        "inputValidation.infoBorder": c.denim,
        "dropdown.background": c.mantle,
        "dropdown.listBackground": c.mantle,
        "dropdown.border": c.surface1,
        "dropdown.foreground": c.text,
        "button.background": c.orange,
        "button.foreground": c.crust,
        "button.hoverBackground": c.orange_hi,
        "button.secondaryBackground": c.surface1,
        "button.secondaryForeground": c.text,
        "button.secondaryHoverBackground": c.surface2,
        "button.border": "#00000000",
        "checkbox.background": c.crust,
        "checkbox.border": c.surface1,
        "checkbox.foreground": c.yellow,
        "badge.background": c.surface2,
        "badge.foreground": c.text_hi,
        "progressBar.background": c.orange,
        "keybindingLabel.background": c.surface0,
        "keybindingLabel.foreground": c.text,
        "keybindingLabel.border": c.surface1,
        "keybindingLabel.bottomBorder": c.surface2,
        "toolbar.hoverBackground": c.surface0,
        "extensionButton.prominentBackground": c.orange,
        "extensionButton.prominentForeground": c.crust,
        "extensionButton.prominentHoverBackground": c.orange_hi,
        "extensionBadge.remoteBackground": c.orange,
        "extensionBadge.remoteForeground": c.crust,
        "extensionIcon.starForeground": c.yellow,
        "settings.headerForeground": c.text_hi,
        "settings.modifiedItemIndicator": c.orange,
        "settings.focusedRowBackground": a(c.surface0, 0.6),
        "settings.rowHoverBackground": a(c.surface0, 0.4),
        "welcomePage.tileBackground": c.mantle,
        "walkThrough.embeddedEditorBackground": c.crust,
        # quick input, menus, notifications
        "quickInput.background": c.mantle,
        "quickInput.foreground": c.text,
        "quickInputTitle.background": c.crust,
        "quickInputList.focusBackground": c.surface1,
        "quickInputList.focusForeground": c.text_hi,
        "pickerGroup.foreground": c.orange,
        "pickerGroup.border": c.surface1,
        "menu.background": c.mantle,
        "menu.foreground": c.text,
        "menu.selectionBackground": c.surface1,
        "menu.selectionForeground": c.text_hi,
        "menu.separatorBackground": c.surface1,
        "menu.border": c.surface0,
        "menubar.selectionBackground": c.surface0,
        "notifications.background": c.mantle,
        "notifications.foreground": c.text,
        "notifications.border": c.surface1,
        "notificationCenterHeader.background": c.crust,
        "notificationLink.foreground": c.denim,
        "notificationsErrorIcon.foreground": c.red_hi,
        "notificationsWarningIcon.foreground": c.yellow,
        "notificationsInfoIcon.foreground": c.denim,
        "notificationToast.border": c.surface1,
        "commandCenter.background": c.mantle,
        "commandCenter.foreground": c.subtext0,
        "commandCenter.border": c.surface0,
        "commandCenter.activeBackground": c.surface0,
        "commandCenter.activeForeground": c.text,
        # panel & terminal
        "panel.background": c.mantle,
        "panel.border": c.surface0,
        "panelTitle.activeForeground": c.text_hi,
        "panelTitle.activeBorder": c.orange,
        "panelTitle.inactiveForeground": c.overlay1,
        "panelSection.border": c.surface0,
        "panelInput.border": c.surface1,
        "outputView.background": c.mantle,
        "terminal.background": c.mantle,
        "terminal.foreground": c.text,
        "terminal.border": c.surface0,
        "terminal.selectionBackground": c.surface2,
        "terminalCursor.foreground": c.yellow,
        "terminalCursor.background": c.base,
        "terminal.findMatchBackground": a(c.orange, 0.45),
        "terminal.findMatchHighlightBackground": a(c.yellow, 0.22),
        "terminalCommandDecoration.defaultBackground": c.overlay0,
        "terminalCommandDecoration.successBackground": c.green,
        "terminalCommandDecoration.errorBackground": c.red_hi,
        # status bar — espresso strip with a burnt-orange remote "bullet"
        "statusBar.background": c.crust,
        "statusBar.foreground": c.subtext0,
        "statusBar.border": c.crust,
        "statusBar.focusBorder": c.orange,
        "statusBar.noFolderBackground": c.crust,
        "statusBar.noFolderForeground": c.subtext0,
        "statusBar.debuggingBackground": c.red,
        "statusBar.debuggingForeground": c.text_hi,
        "statusBar.debuggingBorder": c.red,
        "statusBarItem.remoteBackground": c.orange,
        "statusBarItem.remoteForeground": c.crust,
        "statusBarItem.remoteHoverBackground": c.orange_hi,
        "statusBarItem.hoverBackground": c.surface0,
        "statusBarItem.activeBackground": c.surface1,
        "statusBarItem.prominentBackground": c.surface1,
        "statusBarItem.prominentForeground": c.text_hi,
        "statusBarItem.prominentHoverBackground": c.surface2,
        "statusBarItem.errorBackground": c.red,
        "statusBarItem.errorForeground": c.text_hi,
        "statusBarItem.warningBackground": c.yellow,
        "statusBarItem.warningForeground": c.crust,
        "statusBarItem.compactHoverBackground": c.surface0,
        "statusBarItem.focusBorder": c.orange,
        # git decorations / SCM
        "gitDecoration.addedResourceForeground": c.green_hi,
        "gitDecoration.modifiedResourceForeground": c.yellow,
        "gitDecoration.deletedResourceForeground": c.red_hi,
        "gitDecoration.renamedResourceForeground": c.sage,
        "gitDecoration.untrackedResourceForeground": c.green,
        "gitDecoration.ignoredResourceForeground": c.overlay0,
        "gitDecoration.conflictingResourceForeground": c.orange,
        "gitDecoration.submoduleResourceForeground": c.denim,
        "gitDecoration.stageModifiedResourceForeground": c.yellow_hi,
        "gitDecoration.stageDeletedResourceForeground": c.red_hi,
        "scmGraph.historyItemRefColor": c.orange,
        "scmGraph.historyItemRemoteRefColor": c.denim,
        "scmGraph.historyItemBaseRefColor": c.sage,
        "scmGraph.foreground1": c.yellow,
        "scmGraph.foreground2": c.orange,
        "scmGraph.foreground3": c.green,
        "scmGraph.foreground4": c.sage,
        "scmGraph.foreground5": c.clay,
        # debug / testing / misc
        "debugToolBar.background": c.mantle,
        "debugIcon.breakpointForeground": c.red_hi,
        "editor.stackFrameHighlightBackground": a(c.yellow, 0.15),
        "editor.focusedStackFrameHighlightBackground": a(c.green, 0.15),
        "testing.iconPassed": c.green,
        "testing.iconFailed": c.red_hi,
        "testing.iconQueued": c.yellow,
        "testing.runAction": c.green,
        "charts.foreground": c.text,
        "charts.lines": c.surface2,
        "charts.red": c.red_hi,
        "charts.orange": c.orange,
        "charts.yellow": c.yellow,
        "charts.green": c.green,
        "charts.blue": c.denim,
        "charts.purple": c.clay,
        "chat.requestBackground": a(c.surface0, 0.6),
        "chat.slashCommandForeground": c.yellow,
        "chat.avatarBackground": c.surface1,
        "inlineChat.background": c.mantle,
        "inlineChat.border": c.surface1,
    }
    colors.update(layered(f))
    for i, name in enumerate(ansi_names):
        colors[f"terminal.ansi{name}"] = f.ansi[i]
        colors[f"terminal.ansiBright{name}"] = f.ansi[i + 8]

    def font(st):
        return " ".join(s for s in ("italic", "bold", "underline", "strikethrough") if s in st)

    token_colors = []
    for scope, color, st in scope_rules(f):
        s = {"foreground": color}
        if font(st):
            s["fontStyle"] = font(st)
        token_colors.append({"scope": [x.strip() for x in scope.split(",")], "settings": s})

    def sem(role):
        color, st = f.syntax(role)
        return {"foreground": color, **({"fontStyle": font(st)} if font(st) else {})} if st else color

    semantic = {
        "namespace": sem("namespace"),
        "type": sem("type"), "class": sem("type"), "interface": sem("type"),
        "enum": sem("type"), "struct": sem("type"),
        "typeParameter": {"foreground": f.sage, "fontStyle": "italic"},
        "type.defaultLibrary": sem("type.builtin"),
        "function": sem("function"), "method": sem("function"), "macro": sem("decorator"),
        "function.defaultLibrary": sem("function.builtin"),
        "decorator": sem("decorator"),
        "parameter": sem("parameter"),
        "property": sem("property"),
        "enumMember": sem("constant"),
        "variable": sem("variable"),
        "variable.readonly.defaultLibrary": sem("constant"),
        "selfKeyword": sem("variable.builtin"), "selfParameter": sem("variable.builtin"),
        "builtinConstant": sem("constant"),
        "keyword": sem("keyword"), "string": sem("string"), "number": sem("number"),
        "regexp": sem("regexp"), "comment": sem("comment"), "label": sem("decorator"),
        "*.deprecated": {"fontStyle": "strikethrough"},
    }
    return {
        "$schema": "vscode://schemas/color-theme",
        "name": f.name,
        "type": "dark" if f.dark else "light",
        "semanticHighlighting": True,
        "colors": colors,
        "tokenColors": token_colors,
        "semanticTokenColors": semantic,
    }




def package():
    return {
        "name": "subway-seat",
        "displayName": "Subway Seat",
        "description": "Walnut-brown 1970s NYC subway theme: parchment text, harvest gold, burnt orange, "
        "avocado. Dark, deep dark and light.",
        "version": VERSION,
        "publisher": "oddurs",
        "license": "MIT",
        "icon": "icon.png",
        "galleryBanner": {"color": "#362619", "theme": "dark"},
        "repository": {"type": "git", "url": REPO},
        "homepage": REPO,
        "bugs": {"url": f"{REPO}/issues"},
        "engines": {"vscode": "^1.85.0"},
        "categories": ["Themes"],
        "keywords": ["theme", "dark", "light", "brown", "retro", "70s", "warm", "vintage", "subway seat"],
        "contributes": {
            "themes": [
                {"label": f.name, "uiTheme": "vs-dark" if f.dark else "vs", "path": f"./themes/{f.slug}-color-theme.json"}
                for f in p.FLAVORS
            ]
        },
    }


README = """# Subway Seat

A walnut-brown color theme from a 1970s subway car: parchment text, harvest gold, burnt orange and avocado, with orange bucket seats and wood paneling in mind.

- **Subway Seat**: Walnut, the original dark flavor
- **Subway Seat Tunnel**: the late local after midnight, a deeper dark
- **Subway Seat Enamel**: cream enamel panels in the morning sun, the light one

The workbench is layered on purpose: one chrome ground, grooves instead of lines, popovers lifted onto paper, and every hover and selection a thin wash of text color, so they sit right on any surface. It also themes the AI panels in VS Code, Cursor, Windsurf and Kiro.

Subway Seat is available for ~90 apps, from Ghostty and Neovim to Claude Code: [github.com/oddurs/subway-seat](https://github.com/oddurs/subway-seat).
"""

CONTENT_TYPES = """<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension=".json" ContentType="application/json"/><Default Extension=".vsixmanifest" ContentType="text/xml"/><Default Extension=".md" ContentType="text/markdown"/><Default Extension=".png" ContentType="image/png"/><Default Extension=".txt" ContentType="text/plain"/></Types>
"""


def vsix_manifest(pkg):
    from xml.sax.saxutils import escape

    props = {
        "Microsoft.VisualStudio.Code.Engine": pkg["engines"]["vscode"],
        "Microsoft.VisualStudio.Code.ExtensionDependencies": "",
        "Microsoft.VisualStudio.Code.ExtensionPack": "",
        "Microsoft.VisualStudio.Code.ExtensionKind": "ui,workspace,web",
        "Microsoft.VisualStudio.Code.LocalizedLanguages": "",
        "Microsoft.VisualStudio.Services.Links.Source": REPO,
        "Microsoft.VisualStudio.Services.Links.GitHub": REPO,
        "Microsoft.VisualStudio.Services.Links.Support": f"{REPO}/issues",
        "Microsoft.VisualStudio.Services.Links.Learn": REPO,
        "Microsoft.VisualStudio.Services.Branding.Color": pkg["galleryBanner"]["color"],
        "Microsoft.VisualStudio.Services.Branding.Theme": pkg["galleryBanner"]["theme"],
        "Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown": "true",
        "Microsoft.VisualStudio.Services.Content.Pricing": "Free",
    }
    prop_xml = "".join(f'<Property Id="{k}" Value="{escape(v)}" />' for k, v in props.items())
    tags = ",".join(pkg["keywords"] + ["theme", "color-theme", "__web_extension"])
    return f"""<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="{pkg['name']}" Version="{pkg['version']}" Publisher="{pkg['publisher']}" />
    <DisplayName>{escape(pkg['displayName'])}</DisplayName>
    <Description xml:space="preserve">{escape(pkg['description'])}</Description>
    <Tags>{escape(tags)}</Tags>
    <Categories>Themes</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Properties>{prop_xml}</Properties>
    <License>extension/LICENSE.txt</License>
    <Icon>extension/icon.png</Icon>
  </Metadata>
  <Installation><InstallationTarget Id="Microsoft.VisualStudio.Code"/></Installation>
  <Dependencies/>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE.txt" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/icon.png" Addressable="true" />
  </Assets>
</PackageManifest>
"""


def vsix(pkg, themes):
    """A .vsix is a zip: two manifests plus the extension folder. Built here so
    it's deterministic and downloadable; `vsce publish --packagePath` ships it."""
    import io
    import zipfile
    from pathlib import Path

    root = Path(__file__).resolve().parent.parent
    entries = {
        "[Content_Types].xml": CONTENT_TYPES,
        "extension.vsixmanifest": vsix_manifest(pkg),
        "extension/package.json": json.dumps(pkg, indent=2) + "\n",
        "extension/README.md": README,
        "extension/LICENSE.txt": (root / "LICENSE").read_text(),
        "extension/icon.png": (root / "assets" / "icon.png").read_bytes(),
        **{f"extension/{path}": body for path, body in themes.items()},
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for name, body in entries.items():
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, body)
    return buf.getvalue()


def build(flavors):
    themes = {f"themes/{f.slug}-color-theme.json": json.dumps(theme(f), indent=2) + "\n" for f in flavors}
    outs = [
        Out(path, body, flavor=f.id, dest="packaged in the extension", lang="json")
        for (path, body), f in zip(themes.items(), flavors)
    ]
    pkg = package()
    outs.append(Out("package.json", json.dumps(pkg, indent=2) + "\n", lang="json"))
    outs.append(Out("README.md", README, lang="text"))
    outs.append(Out(f"subway-seat-{VERSION}.vsix", vsix(pkg, themes),
                    dest=f"code --install-extension subway-seat-{VERSION}.vsix"))
    return outs
