// Generated by build.py from palette.py — edit the palette, not this file.
import * as stylex from "@stylexjs/stylex";

// Decorative colors: see build.py's ART note.
export const art = stylex.defineVars({
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#E0956C",
});
