// Generated by build.py from palette.py — edit the palette, not this file.
import * as stylex from "@stylexjs/stylex";
import { art } from "./art.stylex";

export const walnut = stylex.createTheme(art, {
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#E0956C",
});

export const tunnel = stylex.createTheme(art, {
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#E0956C",
});

export const enamel = stylex.createTheme(art, {
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#E0956C",
});

export const moquette = stylex.createTheme(art, {
  red: "#DB6052",
  orange: "#DE8946",
  yellow: "#F2C03F",
  green: "#77C581",
  sage: "#54B4B5",
  denim: "#7595DA",
  clay: "#AE9EDC",
});

export const deep = stylex.createTheme(art, {
  red: "#DB6052",
  orange: "#DE8946",
  yellow: "#F2C03F",
  green: "#77C581",
  sage: "#54B4B5",
  denim: "#7595DA",
  clay: "#AE9EDC",
});

export const portland = stylex.createTheme(art, {
  red: "#DB6052",
  orange: "#DE8946",
  yellow: "#F2C03F",
  green: "#77C581",
  sage: "#54B4B5",
  denim: "#7595DA",
  clay: "#AE9EDC",
});
