// Generated by build.py from palette.py — edit the palette, not this file.
import * as stylex from "@stylexjs/stylex";
import { art } from "./art.stylex";

export const walnut = stylex.createTheme(art, {
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#F4A87E",
  page: "#1A120B",
});

export const tunnel = stylex.createTheme(art, {
  red: "#E05C45",
  orange: "#EC7F31",
  yellow: "#F3BF45",
  green: "#ADB956",
  sage: "#86AD95",
  denim: "#7F9BAE",
  clay: "#F4A87E",
  page: "#100B06",
});

export const enamel = stylex.createTheme(art, {
  red: "#C04331",
  orange: "#CA661B",
  yellow: "#CA972A",
  green: "#8D9A36",
  sage: "#669279",
  denim: "#628299",
  clay: "#C2764D",
  page: "#FAF4E9",
});

export const moquette = stylex.createTheme(art, {
  red: "#DB6052",
  orange: "#DE8946",
  yellow: "#F2C03F",
  green: "#77C581",
  sage: "#54B4B5",
  denim: "#7595DA",
  clay: "#AE9EDC",
  page: "#0F141F",
});

export const deep = stylex.createTheme(art, {
  red: "#DB6052",
  orange: "#DE8946",
  yellow: "#F2C03F",
  green: "#77C581",
  sage: "#54B4B5",
  denim: "#7595DA",
  clay: "#AE9EDC",
  page: "#080B14",
});

export const portland = stylex.createTheme(art, {
  red: "#BE4439",
  orange: "#C46A26",
  yellow: "#C59A26",
  green: "#47A65D",
  sage: "#2E9799",
  denim: "#405DC4",
  clay: "#9482C5",
  page: "#EFF4FF",
});

export const guimard = stylex.createTheme(art, {
  red: "#C7665B",
  orange: "#CA9245",
  yellow: "#F1BF4B",
  green: "#70CAA9",
  sage: "#549B9F",
  denim: "#709BC8",
  clay: "#FAB49C",
  page: "#101513",
});

export const catacombes = stylex.createTheme(art, {
  red: "#C7665B",
  orange: "#CA9245",
  yellow: "#F1BF4B",
  green: "#70CAA9",
  sage: "#549B9F",
  denim: "#709BC8",
  clay: "#FAB49C",
  page: "#080D0B",
});

export const carrelage = stylex.createTheme(art, {
  red: "#AB4940",
  orange: "#A47226",
  yellow: "#C69A2C",
  green: "#4CAA8B",
  sage: "#2E8186",
  denim: "#4E81B4",
  clay: "#DA937A",
  page: "#F3F6F5",
});
